# Generated by Django 5.2.16 on 2026-08-06 11:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendance_absence_reason_review_note_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='absence_reason',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='absence_reason_by',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='absence_reason_review_note',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='absence_reason_reviewed_at',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='absence_reason_reviewed_by',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='absence_reason_status',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='absence_reason_submitted_at',
        ),
        migrations.AddField(
            model_name='attendance',
            name='approval_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='late_arrivals_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='auto_marked_absent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='late_request_status',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='attendance',
            name='minutes_late',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('PRESENT', 'Present'), ('PRESENT_LATE', 'Present (Late)'), ('PRESENT_LATE_APPROVED', 'Present (Late Approved)'), ('ABSENT', 'Absent'), ('ON_LEAVE', 'On Leave'), ('OFF_DUTY', 'Off Duty')], default='SCHEDULED', max_length=25),
        ),
        migrations.CreateModel(
            name='LateArrivalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('reason', models.CharField(max_length=255)),
                ('explanation', models.TextField(blank=True)),
                ('attachment', models.ImageField(blank=True, null=True, upload_to='late_arrival_attachments/%Y/%m/')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('minutes_late_at_submission', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='late_arrival_requests', to='attendance.attendance')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='late_arrival_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
