# Generated by Django 5.2.16 on 2026-08-07 08:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_remove_attendance_absence_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notification_type', models.CharField(choices=[('GRACE_PERIOD_ENDING', 'Grace Period Ending Soon'), ('AUTO_ABSENT', 'Automatically Marked Absent'), ('LATE_REQUEST_SUBMITTED', 'Late Request Submitted'), ('LATE_REQUEST_APPROVED', 'Late Request Approved'), ('LATE_REQUEST_REJECTED', 'Late Request Rejected'), ('NEW_LATE_REQUEST', 'New Late Arrival Request'), ('PENDING_APPROVAL_REMINDER', 'Pending Approval Reminder')], max_length=32)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='attendance.attendance')),
                ('late_arrival_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='attendance.latearrivalrequest')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
