# Generated by Django 5.2.16 on 2026-07-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_employeeprofile_pin_attempts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='employee_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
