# Generated by Django 5.2.16 on 2026-07-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_employeeprofile_employee_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='pin_must_change',
            field=models.BooleanField(default=False),
        ),
    ]
