# Generated by Django 5.2.16 on 2026-07-27 07:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.CharField(choices=[('FUEL', 'Fuel'), ('EQUIPMENT', 'Equipment / Uniforms'), ('VEHICLE_MAINTENANCE', 'Vehicle Maintenance'), ('RENT_UTILITIES', 'Rent / Utilities'), ('LICENSES', 'Licenses / Permits'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('vendor_name', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expense_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=10)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-expense_date'],
            },
        ),
    ]
