# Generated by Django 5.2.16 on 2026-07-17 11:15

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salarystructure',
            options={'ordering': ['-effective_from']},
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='effective_from',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='effective_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='overtime_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='payment_frequency',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('WEEKLY', 'Weekly'), ('BI_WEEKLY', 'Bi-Weekly')], default='MONTHLY', max_length=12),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structures', to='staff.employeeprofile'),
        ),
    ]
