# Generated by Django 5.2.16 on 2026-07-18 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_alter_salarystructure_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarystructure',
            name='effective_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='payment_frequency',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('WEEKLY', 'Weekly'), ('BI_WEEKLY', 'Bi-Weekly')], default='MONTHLY', max_length=20),
        ),
    ]
