# Generated by Django 5.2.16 on 2026-07-29 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_alter_salarystructure_effective_from_and_more'),
        ('staff', '0004_employeeprofile_pin_must_change'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salarystructure',
            options={},
        ),
        migrations.RemoveField(
            model_name='salarystructure',
            name='effective_from',
        ),
        migrations.RemoveField(
            model_name='salarystructure',
            name='effective_to',
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structure', to='staff.employeeprofile'),
        ),
    ]
