# Generated by Django 5.2.16 on 2026-08-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_incidentactivity_latitude_incidentactivity_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentactivity',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='incidentactivity',
            name='longitude',
        ),
        migrations.AddField(
            model_name='incident',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
