# Generated by Django 5.2.16 on 2026-07-31 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_iplockout_user_policy_accepted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='failed_password_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='password_locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
