import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, Download, FileSpreadsheet, Printer } from 'lucide-react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';
import { getInvoices } from '../../api/invoicesApi';
import type { Invoice } from '../../types/invoices';

function formatKES(value: number): string {
  return new Intl.NumberFormat('en-KE', { style: 'currency', currency: 'KES' }).format(value);
}

function daysOverdue(dueDate: string): number {
  const today = new Date();
  const due = new Date(dueDate);
  return Math.max(0, Math.floor((today.getTime() - due.getTime()) / (1000 * 60 * 60 * 24)));
}

export default function AccountsReceivableReportPage() {
  const [invoices, setInvoices] = useState<Invoice[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [clientFilter, setClientFilter] = useState('');

  useEffect(() => {
    getInvoices()
      .then(setInvoices)
      .catch((err) => {
        console.error(err);
        setError('Failed to load receivables data.');
      })
      .finally(() => setIsLoading(false));
  }, []);

  const outstanding = useMemo(
    () => invoices.filter((inv) => inv.status !== 'PAID' && inv.status !== 'CANCELLED'),
    [invoices]
  );

  const clients = useMemo(
    () => Array.from(new Set(outstanding.map((inv) => inv.client_name))).sort(),
    [outstanding]
  );

  const filtered = useMemo(
    () => (clientFilter ? outstanding.filter((inv) => inv.client_name === clientFilter) : outstanding),
    [outstanding, clientFilter]
  );

  const rows = useMemo(
    () =>
      filtered
        .map((inv) => ({
          invoice: inv,
          daysOverdue: daysOverdue(inv.due_date),
        }))
        .sort((a, b) => b.daysOverdue - a.daysOverdue),
    [filtered]
  );

  const summary = useMemo(() => {
    const totalOutstanding = rows.reduce((sum, r) => sum + parseFloat(r.invoice.subtotal), 0);
    const overdueCount = rows.filter((r) => r.daysOverdue > 0).length;
    const overdueAmount = rows
      .filter((r) => r.daysOverdue > 0)
      .reduce((sum, r) => sum + parseFloat(r.invoice.subtotal), 0);
    return { totalOutstanding, overdueCount, overdueAmount, count: rows.length };
  }, [rows]);

  function agingBucket(days: number): string {
    if (days === 0) return 'Current';
    if (days <= 30) return '1–30 days';
    if (days <= 60) return '31–60 days';
    return '60+ days';
  }

  function exportPDF() {
    const doc = new jsPDF({ orientation: 'landscape' });
    doc.setFontSize(16);
    doc.text('Accounts Receivable Report', 14, 16);
    doc.setFontSize(10);
    doc.text(`Generated: ${new Date().toLocaleDateString('en-KE')}`, 14, 23);

    autoTable(doc, {
      startY: 30,
      head: [['Invoice #', 'Client', 'Due Date', 'Amount', 'Days Overdue', 'Aging', 'Status']],
      body: rows.map((r) => [
        r.invoice.invoice_number,
        r.invoice.client_name,
        r.invoice.due_date,
        formatKES(parseFloat(r.invoice.subtotal)),
        r.daysOverdue > 0 ? r.daysOverdue : '—',
        agingBucket(r.daysOverdue),
        r.invoice.status,
      ]),
      styles: { fontSize: 9, cellPadding: 3 },
      headStyles: { fillColor: [27, 42, 110] },
    });

    const pageHeight = doc.internal.pageSize.getHeight();
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text('Generated by Erip Technologies · 0710951879', 14, pageHeight - 10);

    doc.save(`accounts-receivable-${new Date().toISOString().slice(0, 10)}.pdf`);
  }

  function exportExcel() {
    const worksheet = XLSX.utils.json_to_sheet(
      rows.map((r) => ({
        'Invoice #': r.invoice.invoice_number,
        Client: r.invoice.client_name,
        'Due Date': r.invoice.due_date,
        Amount: parseFloat(r.invoice.subtotal),
        'Days Overdue': r.daysOverdue,
        Aging: agingBucket(r.daysOverdue),
        Status: r.invoice.status,
      }))
    );
    const workbook = XLSX.utils.book_new();
    workbook.Props = { Author: 'Erip Technologies', Company: 'Crimecurb Security Services' };
    XLSX.utils.book_append_sheet(workbook, worksheet, 'Accounts Receivable');
    XLSX.writeFile(workbook, `accounts-receivable-${new Date().toISOString().slice(0, 10)}.xlsx`);
  }

  return (
    <div>
      <Link to="/reports" className="inline-flex items-center gap-1 text-sm text-slate-500 hover:text-slate-700 mb-4 print:hidden">
        <ArrowLeft size={14} /> Back to Reports
      </Link>

      <div className="flex items-start justify-between flex-wrap gap-3 mb-6">
        <div>
          <p className="text-[11px] font-mono font-semibold uppercase tracking-[2px] text-crimecurb-red mb-1">
            Financial · Reports
          </p>
          <h1 className="font-display text-2xl font-bold text-slate-800">Accounts Receivable Report</h1>
          <p className="text-sm text-slate-500 mt-1">Amounts owed to the company — unpaid invoices.</p>
        </div>
        <div className="flex gap-2 print:hidden">
          <button onClick={exportPDF} className="flex items-center gap-1.5 bg-white border border-slate-200 hover:border-slate-300 text-slate-700 text-sm font-medium px-3 py-2 rounded-lg transition-colors">
            <Download size={14} /> PDF
          </button>
          <button onClick={exportExcel} className="flex items-center gap-1.5 bg-white border border-slate-200 hover:border-slate-300 text-slate-700 text-sm font-medium px-3 py-2 rounded-lg transition-colors">
            <FileSpreadsheet size={14} /> Excel
          </button>
          <button onClick={() => window.print()} className="flex items-center gap-1.5 bg-crimecurb-navy hover:opacity-90 text-white text-sm font-medium px-3 py-2 rounded-lg transition-colors">
            <Printer size={14} /> Print
          </button>
        </div>
      </div>

      {isLoading && <p className="text-slate-500">Loading...</p>}
      {error && <p className="text-red-600">{error}</p>}

      {!isLoading && !error && (
        <>
          <div className="grid grid-cols-2 lg:grid-cols-4 gap-3.5 mb-6">
            <div className="bg-white rounded-xl border border-slate-200 p-4">
              <p className="text-[10.5px] font-semibold uppercase tracking-wide text-slate-500 mb-1">Outstanding Invoices</p>
              <p className="font-mono text-2xl font-bold text-slate-800">{summary.count}</p>
            </div>
            <div className="bg-white rounded-xl border border-slate-200 p-4">
              <p className="text-[10.5px] font-semibold uppercase tracking-wide text-slate-500 mb-1">Total Outstanding</p>
              <p className="font-mono text-2xl font-bold text-slate-800">{formatKES(summary.totalOutstanding)}</p>
            </div>
            <div className="bg-white rounded-xl border border-slate-200 p-4">
              <p className="text-[10.5px] font-semibold uppercase tracking-wide text-slate-500 mb-1">Overdue Invoices</p>
              <p className={`font-mono text-2xl font-bold ${summary.overdueCount > 0 ? 'text-red-600' : 'text-slate-800'}`}>
                {summary.overdueCount}
              </p>
            </div>
            <div className="bg-white rounded-xl border border-slate-200 p-4">
              <p className="text-[10.5px] font-semibold uppercase tracking-wide text-slate-500 mb-1">Overdue Amount</p>
              <p className={`font-mono text-2xl font-bold ${summary.overdueAmount > 0 ? 'text-red-600' : 'text-slate-800'}`}>
                {formatKES(summary.overdueAmount)}
              </p>
            </div>
          </div>

          <div className="bg-white rounded-xl border border-slate-200 p-4 mb-6 print:hidden">
            <label className="block text-xs text-slate-500 mb-1">Filter by Client</label>
            <select
              value={clientFilter}
              onChange={(e) => setClientFilter(e.target.value)}
              className="w-full sm:w-64 px-3 py-2 rounded border border-slate-300 text-sm"
            >
              <option value="">All Clients</option>
              {clients.map((c) => (
                <option key={c} value={c}>{c}</option>
              ))}
            </select>
          </div>

          <div className="bg-white rounded-xl border border-slate-200 overflow-hidden">
            <table className="w-full text-sm text-left">
              <thead className="bg-slate-50 text-slate-500 uppercase text-xs">
                <tr>
                  <th className="px-4 py-3">Invoice #</th>
                  <th className="px-4 py-3">Client</th>
                  <th className="px-4 py-3">Due Date</th>
                  <th className="px-4 py-3">Amount</th>
                  <th className="px-4 py-3">Aging</th>
                  <th className="px-4 py-3">Status</th>
                </tr>
              </thead>
              <tbody>
                {rows.map((r) => (
                  <tr key={r.invoice.id} className="border-t border-slate-100">
                    <td className="px-4 py-3 font-medium text-slate-800">{r.invoice.invoice_number}</td>
                    <td className="px-4 py-3 text-slate-600">{r.invoice.client_name}</td>
                    <td className="px-4 py-3 text-slate-600">{r.invoice.due_date}</td>
                    <td className="px-4 py-3 text-slate-800">{formatKES(parseFloat(r.invoice.subtotal))}</td>
                    <td className="px-4 py-3">
                      <span
                        className={`px-2 py-1 rounded text-xs font-medium ${
                          r.daysOverdue === 0
                            ? 'bg-slate-100 text-slate-500'
                            : r.daysOverdue <= 30
                            ? 'bg-amber-100 text-amber-700'
                            : 'bg-red-100 text-red-700'
                        }`}
                      >
                        {agingBucket(r.daysOverdue)}
                      </span>
                    </td>
                    <td className="px-4 py-3 text-slate-600">{r.invoice.status}</td>
                  </tr>
                ))}
                {rows.length === 0 && (
                  <tr>
                    <td colSpan={6} className="px-4 py-6 text-center text-slate-400">
                      No outstanding invoices — fully collected.
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>

          <div className="text-center text-xs text-slate-400 mt-8 pt-4 border-t border-slate-200">
            <p>Generated by Erip <span className="text-crimecurb-red font-semibold">⚡</span> Technologies</p>
            <p>0710951879</p>
          </div>
        </>
      )}
    </div>
  );
}