import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, Download, FileSpreadsheet, Printer } from 'lucide-react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';
import { getExpenses } from '../../api/expensesApi';
import type { Expense } from '../../types/expenses';

function formatKES(value: number): string {
  return new Intl.NumberFormat('en-KE', { style: 'currency', currency: 'KES' }).format(value);
}

function daysUntilOrPast(dueDate: string | null): number | null {
  if (!dueDate) return null;
  const today = new Date();
  const due = new Date(dueDate);
  return Math.floor((today.getTime() - due.getTime()) / (1000 * 60 * 60 * 24));
}

export default function AccountsPayableReportPage() {
  const [expenses, setExpenses] = useState<Expense[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    getExpenses()
      .then(setExpenses)
      .catch((err) => {
        console.error(err);
        setError('Failed to load payables data.');
      })
      .finally(() => setIsLoading(false));
  }, []);

  const outstanding = useMemo(
    () => expenses.filter((e) => e.status === 'PENDING' || e.status === 'OVERDUE'),
    [expenses]
  );

  const rows = useMemo(
    () =>
      outstanding
        .map((e) => ({ expense: e, daysPastDue: daysUntilOrPast(e.due_date) }))
        .sort((a, b) => (b.daysPastDue ?? -999) - (a.daysPastDue ?? -999)),
    [outstanding]
  );

  const summary = useMemo(() => {
    const total = rows.reduce((sum, r) => sum + parseFloat(r.expense.amount), 0);
    const overdue = rows.filter((r) => r.daysPastDue !== null && r.daysPastDue > 0);
    const overdueAmount = overdue.reduce((sum, r) => sum + parseFloat(r.expense.amount), 0);
    return { total, count: rows.length, overdueCount: overdue.length, overdueAmount };
  }, [rows]);

  function exportPDF() {
    const doc = new jsPDF({ orientation: 'landscape' });
    doc.setFontSize(16);
    doc.text('Accounts Payable Report', 14, 16);
    doc.setFontSize(10);
    doc.text(`Generated: ${new Date().toLocaleDateString('en-KE')}`, 14, 23);

    autoTable(doc, {
      startY: 30,
      head: [['Description', 'Vendor', 'Amount', 'Due Date', 'Days Past Due', 'Status']],
      body: rows.map((r) => [
        r.expense.description,
        r.expense.vendor_name || '—',
        formatKES(parseFloat(r.expense.amount)),
        r.expense.due_date ?? '—',
        r.daysPastDue !== null && r.daysPastDue > 0 ? r.daysPastDue : '—',
        r.expense.status,
      ]),
      styles: { fontSize: 9, cellPadding: 3 },
      headStyles: { fillColor: [27, 42, 110] },
    });

    const pageHeight = doc.internal.pageSize.getHeight();
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text('Generated by Erip Technologies · 0710951879', 14, pageHeight - 10);

    doc.save(`accounts-payable-${new Date().toISOString().slice(0, 10)}.pdf`);
  }

  function exportExcel() {
    const worksheet = XLSX.utils.json_to_sheet(
      rows.map((r) => ({
        Description: r.expense.description,
        Vendor: r.expense.vendor_name || '—',
        Amount: parseFloat(r.expense.amount),
        'Due Date': r.expense.due_date ?? '—',
        'Days Past Due': r.daysPastDue !== null && r.daysPastDue > 0 ? r.daysPastDue : 0,
        Status: r.expense.status,
      }))
    );
    const workbook = XLSX.utils.book_new();
    workbook.Props = { Author: 'Erip Technologies', Company: 'Crimecurb Security Services' };
    XLSX.utils.book_append_sheet(workbook, worksheet, 'Accounts Payable');
    XLSX.writeFile(workbook, `accounts-payable-${new Date().toISOString().slice(0, 10)}.xlsx`);
  }

  return (
    <div>
      <Link to="/reports" className="inline-flex items-center gap-1 text-sm text-slate-500 hover:text-slate-700 mb-4 print:hidden">
        <ArrowLeft size={14} /> Back to Reports
      </Link>

      <div className="flex items-start justify-between flex-wrap gap-3 mb-6">
        <div>
          <p className="text-[11px] font-mono font-semibold uppercase tracking-[2px] text-crimecurb-red mb-1">
            Financial · Reports
          </p>
          <h1 className="font-display text-2xl font-bold text-slate-800">Accounts Payable Report</h1>
          <p className="text-sm text-slate-500 mt-1">Amounts owed by the company — unpaid expenses.</p>
        </div>
        <div className="flex gap-2 print:hidden">
          <button onClick={exportPDF} className="flex items-center gap-1.5 bg-white border border-slate-200 hover:border-slate-300 text-slate-700 text-sm font-medium px-3 py-2 rounded-lg transition-colors">
            <Download size={14} /> PDF
          </button>
          <button onClick={exportExcel} className="flex items-center gap-1.5 bg-white border border-slate-200 hover:border-slate-300 text-slate-700 text-sm font-medium px-3 py-2 rounded-lg transition-colors">
            <FileSpreadsheet size={14} /> Excel
          </button>
          <button onClick={() => window.print()} className="flex items-center gap-1.5 bg-crimecurb-navy hover:opacity-90 text-white text-sm font-medium px-3 py-2 rounded-lg transition-colors">
            <Printer size={14} /> Print
          </button>
        </div>
      </div>

      {isLoading && <p className="text-slate-500">Loading...</p>}
      {error && <p className="text-red-600">{error}</p>}

      {!isLoading && !error && (
        <>
          <div className="grid grid-cols-2 lg:grid-cols-4 gap-3.5 mb-6">
            <div className="bg-white rounded-xl border border-slate-200 p-4">
              <p className="text-[10.5px] font-semibold uppercase tracking-wide text-slate-500 mb-1">Outstanding Bills</p>
              <p className="font-mono text-2xl font-bold text-slate-800">{summary.count}</p>
            </div>
            <div className="bg-white rounded-xl border border-slate-200 p-4">
              <p className="text-[10.5px] font-semibold uppercase tracking-wide text-slate-500 mb-1">Total Payable</p>
              <p className="font-mono text-2xl font-bold text-slate-800">{formatKES(summary.total)}</p>
            </div>
            <div className="bg-white rounded-xl border border-slate-200 p-4">
              <p className="text-[10.5px] font-semibold uppercase tracking-wide text-slate-500 mb-1">Overdue</p>
              <p className={`font-mono text-2xl font-bold ${summary.overdueCount > 0 ? 'text-red-600' : 'text-slate-800'}`}>
                {summary.overdueCount}
              </p>
            </div>
            <div className="bg-white rounded-xl border border-slate-200 p-4">
              <p className="text-[10.5px] font-semibold uppercase tracking-wide text-slate-500 mb-1">Overdue Amount</p>
              <p className={`font-mono text-2xl font-bold ${summary.overdueAmount > 0 ? 'text-red-600' : 'text-slate-800'}`}>
                {formatKES(summary.overdueAmount)}
              </p>
            </div>
          </div>

          <div className="bg-white rounded-xl border border-slate-200 overflow-hidden">
            <table className="w-full text-sm text-left">
              <thead className="bg-slate-50 text-slate-500 uppercase text-xs">
                <tr>
                  <th className="px-4 py-3">Description</th>
                  <th className="px-4 py-3">Vendor</th>
                  <th className="px-4 py-3">Amount</th>
                  <th className="px-4 py-3">Due Date</th>
                  <th className="px-4 py-3">Status</th>
                </tr>
              </thead>
              <tbody>
                {rows.map((r) => (
                  <tr key={r.expense.id} className="border-t border-slate-100">
                    <td className="px-4 py-3 font-medium text-slate-800">{r.expense.description}</td>
                    <td className="px-4 py-3 text-slate-600">{r.expense.vendor_name || '—'}</td>
                    <td className="px-4 py-3 text-slate-800">{formatKES(parseFloat(r.expense.amount))}</td>
                    <td className="px-4 py-3 text-slate-600">{r.expense.due_date ?? '—'}</td>
                    <td className="px-4 py-3">
                      <span
                        className={`px-2 py-1 rounded text-xs font-medium ${
                          r.daysPastDue !== null && r.daysPastDue > 0
                            ? 'bg-red-100 text-red-700'
                            : 'bg-amber-100 text-amber-700'
                        }`}
                      >
                        {r.expense.status}
                      </span>
                    </td>
                  </tr>
                ))}
                {rows.length === 0 && (
                  <tr>
                    <td colSpan={5} className="px-4 py-6 text-center text-slate-400">
                      No outstanding payables.
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>

          <div className="text-center text-xs text-slate-400 mt-8 pt-4 border-t border-slate-200">
            <p>Generated by Erip <span className="text-crimecurb-red font-semibold">⚡</span> Technologies</p>
            <p>0710951879</p>
          </div>
        </>
      )}
    </div>
  );
}