import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, Download, FileSpreadsheet, Printer } from 'lucide-react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';
import { getEmployeeProfiles } from '../../api/staffApi';
import type { EmployeeProfile } from '../../types/staff';

type DocStatus = 'Expired' | 'Expiring Soon' | 'Valid' | 'No Expiry Set';

function getDocStatus(expiryDate: string | null): DocStatus {
  if (!expiryDate) return 'No Expiry Set';
  const today = new Date();
  const expiry = new Date(expiryDate);
  const daysUntil = Math.floor((expiry.getTime() - today.getTime()) / (1000 * 60 * 60 * 24));
  if (daysUntil < 0) return 'Expired';
  if (daysUntil <= 30) return 'Expiring Soon';
  return 'Valid';
}

const STATUS_STYLES: Record<DocStatus, string> = {
  Expired: 'bg-red-100 text-red-700',
  'Expiring Soon': 'bg-amber-100 text-amber-700',
  Valid: 'bg-emerald-100 text-emerald-700',
  'No Expiry Set': 'bg-slate-100 text-slate-500',
};

export default function ComplianceReportPage() {
  const [employees, setEmployees] = useState<EmployeeProfile[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [statusFilter, setStatusFilter] = useState('');

  useEffect(() => {
    getEmployeeProfiles()
      .then(setEmployees)
      .catch((err) => {
        console.error(err);
        setError('Failed to load compliance data.');
      })
      .finally(() => setIsLoading(false));
  }, []);

  const docRows = useMemo(() => {
    const rows: Array<{
      employeeName: string;
      employeeNumber: string;
      documentType: string;
      expiryDate: string | null;
      status: DocStatus;
    }> = [];
    employees.forEach((e) => {
      e.documents.forEach((d) => {
        rows.push({
          employeeName: `${e.user.first_name} ${e.user.last_name}`,
          employeeNumber: e.employee_number ?? "N/A",
          documentType: d.document_type,
          expiryDate: d.expiry_date,
          status: getDocStatus(d.expiry_date),
        });
      });
    });
    return rows;
  }, [employees]);

  const employeesWithNoDocuments = useMemo(
    () => employees.filter((e) => e.documents.length === 0 && e.employment_status === 'ACTIVE'),
    [employees]
  );

  const filteredRows = useMemo(
    () => (statusFilter ? docRows.filter((r) => r.status === statusFilter) : docRows),
    [docRows, statusFilter]
  );

  const summary = useMemo(
    () => ({
      expired: docRows.filter((r) => r.status === 'Expired').length,
      expiringSoon: docRows.filter((r) => r.status === 'Expiring Soon').length,
      noDocuments: employeesWithNoDocuments.length,
      totalTracked: docRows.length,
    }),
    [docRows, employeesWithNoDocuments]
  );

  function exportPDF() {
    const doc = new jsPDF({ orientation: 'landscape' });
    doc.setFontSize(16);
    doc.text('Compliance Report', 14, 16);
    doc.setFontSize(10);
    doc.text(`Generated: ${new Date().toLocaleDateString('en-KE')}`, 14, 23);

    autoTable(doc, {
      startY: 30,
      head: [['Employee', 'Employee #', 'Document Type', 'Expiry Date', 'Status']],
      body: filteredRows.map((r) => [
        r.employeeName,
        r.employeeNumber,
        r.documentType,
        r.expiryDate ?? '—',
        r.status,
      ]),
      styles: { fontSize: 9, cellPadding: 3 },
      headStyles: { fillColor: [27, 42, 110] },
    });

    const pageHeight = doc.internal.pageSize.getHeight();
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text('Generated by Erip Technologies · 0710951879', 14, pageHeight - 10);

    doc.save(`compliance-report-${new Date().toISOString().slice(0, 10)}.pdf`);
  }

  function exportExcel() {
    const worksheet = XLSX.utils.json_to_sheet(
      filteredRows.map((r) => ({
        Employee: r.employeeName,
        'Employee #': r.employeeNumber,
        'Document Type': r.documentType,
        'Expiry Date': r.expiryDate ?? '—',
        Status: r.status,
      }))
    );
    const workbook = XLSX.utils.book_new();
    workbook.Props = { Author: 'Erip Technologies', Company: 'Crimecurb Security Services' };
    XLSX.utils.book_append_sheet(workbook, worksheet, 'Compliance');
    XLSX.writeFile(workbook, `compliance-report-${new Date().toISOString().slice(0, 10)}.xlsx`);
  }

  return (
    <div>
      <Link to="/reports" className="inline-flex items-center gap-1 text-sm text-slate-500 hover:text-slate-700 mb-4 print:hidden">
        <ArrowLeft size={14} /> Back to Reports
      </Link>

      <div className="flex items-start justify-between flex-wrap gap-3 mb-6">
        <div>
          <p className="text-[11px] font-mono font-semibold uppercase tracking-[2px] text-crimecurb-red mb-1">
            Executive · Reports
          </p>
          <h1 className="font-display text-2xl font-bold text-slate-800">Compliance Report</h1>
        </div>
        <div className="flex gap-2 print:hidden">
          <button onClick={exportPDF} className="flex items-center gap-1.5 bg-white border border-slate-200 hover:border-slate-300 text-slate-700 text-sm font-medium px-3 py-2 rounded-lg transition-colors">
            <Download size={14} /> PDF
          </button>
          <button onClick={exportExcel} className="flex items-center gap-1.5 bg-white border border-slate-200 hover:border-slate-300 text-slate-700 text-sm font-medium px-3 py-2 rounded-lg transition-colors">
            <FileSpreadsheet size={14} /> Excel
          </button>
          <button onClick={() => window.print()} className="flex items-center gap-1.5 bg-crimecurb-navy hover:opacity-90 text-white text-sm font-medium px-3 py-2 rounded-lg transition-colors">
            <Printer size={14} /> Print
          </button>
        </div>
      </div>

      {isLoading && <p className="text-slate-500">Loading...</p>}
      {error && <p className="text-red-600">{error}</p>}

      {!isLoading && !error && (
        <>
          <div className="grid grid-cols-2 lg:grid-cols-4 gap-3.5 mb-6">
            <div className="bg-white rounded-xl border border-slate-200 p-4">
              <p className="text-[10.5px] font-semibold uppercase tracking-wide text-slate-500 mb-1">Expired</p>
              <p className={`font-mono text-2xl font-bold ${summary.expired > 0 ? 'text-red-600' : 'text-slate-800'}`}>{summary.expired}</p>
            </div>
            <div className="bg-white rounded-xl border border-slate-200 p-4">
              <p className="text-[10.5px] font-semibold uppercase tracking-wide text-slate-500 mb-1">Expiring Soon</p>
              <p className={`font-mono text-2xl font-bold ${summary.expiringSoon > 0 ? 'text-amber-600' : 'text-slate-800'}`}>{summary.expiringSoon}</p>
            </div>
            <div className="bg-white rounded-xl border border-slate-200 p-4">
              <p className="text-[10.5px] font-semibold uppercase tracking-wide text-slate-500 mb-1">No Documents on File</p>
              <p className={`font-mono text-2xl font-bold ${summary.noDocuments > 0 ? 'text-red-600' : 'text-slate-800'}`}>{summary.noDocuments}</p>
            </div>
            <div className="bg-white rounded-xl border border-slate-200 p-4">
              <p className="text-[10.5px] font-semibold uppercase tracking-wide text-slate-500 mb-1">Total Documents Tracked</p>
              <p className="font-mono text-2xl font-bold text-slate-800">{summary.totalTracked}</p>
            </div>
          </div>

          {employeesWithNoDocuments.length > 0 && (
            <div className="bg-red-50 border border-red-200 rounded-xl p-4 mb-6">
              <p className="text-sm font-semibold text-red-700 mb-1">Active employees with zero documents on file:</p>
              <p className="text-sm text-red-600">
                {employeesWithNoDocuments.map((e) => `${e.user.first_name} ${e.user.last_name} (${e.employee_number})`).join(', ')}
              </p>
            </div>
          )}

          <div className="bg-white rounded-xl border border-slate-200 p-4 mb-6 print:hidden">
            <label className="block text-xs text-slate-500 mb-1">Filter by Status</label>
            <select
              value={statusFilter}
              onChange={(e) => setStatusFilter(e.target.value)}
              className="w-full sm:w-64 px-3 py-2 rounded border border-slate-300 text-sm"
            >
              <option value="">All Statuses</option>
              <option value="Expired">Expired</option>
              <option value="Expiring Soon">Expiring Soon</option>
              <option value="Valid">Valid</option>
              <option value="No Expiry Set">No Expiry Set</option>
            </select>
          </div>

          <div className="bg-white rounded-xl border border-slate-200 overflow-hidden">
            <table className="w-full text-sm text-left">
              <thead className="bg-slate-50 text-slate-500 uppercase text-xs">
                <tr>
                  <th className="px-4 py-3">Employee</th>
                  <th className="px-4 py-3">Employee #</th>
                  <th className="px-4 py-3">Document Type</th>
                  <th className="px-4 py-3">Expiry Date</th>
                  <th className="px-4 py-3">Status</th>
                </tr>
              </thead>
              <tbody>
                {filteredRows.map((r, idx) => (
                  <tr key={idx} className="border-t border-slate-100">
                    <td className="px-4 py-3 font-medium text-slate-800">{r.employeeName}</td>
                    <td className="px-4 py-3 text-slate-600">{r.employeeNumber}</td>
                    <td className="px-4 py-3 text-slate-600">{r.documentType}</td>
                    <td className="px-4 py-3 text-slate-600">{r.expiryDate ?? '—'}</td>
                    <td className="px-4 py-3">
                      <span className={`px-2 py-1 rounded text-xs font-medium ${STATUS_STYLES[r.status]}`}>
                        {r.status}
                      </span>
                    </td>
                  </tr>
                ))}
                {filteredRows.length === 0 && (
                  <tr>
                    <td colSpan={5} className="px-4 py-6 text-center text-slate-400">
                      No documents match these filters.
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>

          <div className="text-center text-xs text-slate-400 mt-8 pt-4 border-t border-slate-200">
            <p>Generated by Erip <span className="text-crimecurb-red font-semibold">⚡</span> Technologies</p>
            <p>0710951879</p>
          </div>
        </>
      )}
    </div>
  );
}