import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, Download, FileSpreadsheet, Printer } from 'lucide-react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';
import { getEmployeeProfiles } from '../../api/staffApi';
import type { EmployeeProfile } from '../../types/staff';

const STATUSES = ['ACTIVE', 'ON_LEAVE', 'SUSPENDED', 'TERMINATED'];
const ROLES = ['GUARD', 'SUPERVISOR', 'MANAGER', 'ADMIN'];

export default function EmployeeReportPage() {
  const [employees, setEmployees] = useState<EmployeeProfile[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const [statusFilter, setStatusFilter] = useState('');
  const [roleFilter, setRoleFilter] = useState('');

  useEffect(() => {
    getEmployeeProfiles()
      .then(setEmployees)
      .catch(() => setError('Failed to load employee data.'))
      .finally(() => setIsLoading(false));
  }, []);

  const filtered = useMemo(() => {
    return employees.filter((e) => {
      if (statusFilter && e.employment_status !== statusFilter) return false;
      if (roleFilter && e.user.role !== roleFilter) return false;
      return true;
    });
  }, [employees, statusFilter, roleFilter]);

  const summary = useMemo(() => {
    const total = filtered.length;
    const active = filtered.filter((e) => e.employment_status === 'ACTIVE').length;
    const guards = filtered.filter((e) => e.user.role === 'GUARD').length;
    const management = total - guards;
    return { total, active, guards, management };
  }, [filtered]);

  const chartData = useMemo(() => {
    const byRole: Record<string, number> = {};
    filtered.forEach((e) => {
      const role = e.user.role ?? 'Unknown';
      byRole[role] = (byRole[role] ?? 0) + 1;
    });
    return Object.entries(byRole).sort(([, a], [, b]) => b - a);
  }, [filtered]);

  const maxCount = Math.max(1, ...chartData.map(([, c]) => c));

  function exportPDF() {
    const doc = new jsPDF({ orientation: 'landscape' });
    doc.setFontSize(16);
    doc.text('Employee Report', 14, 16);
    doc.setFontSize(10);
    doc.text(`Generated: ${new Date().toLocaleDateString('en-KE')}`, 14, 23);

    autoTable(doc, {
      startY: 32,
      head: [['Employee #', 'Name', 'Email', 'Phone', 'Role', 'Status', 'Date Employed']],
      body: filtered.map((e) => [
        e.employee_number ?? '—',
        `${e.user.first_name} ${e.user.last_name}`,
        e.user.email,
        e.user.phone_number || '—',
        e.user.role ?? '—',
        e.employment_status,
        e.date_employed,
      ]),
      styles: { fontSize: 9, cellPadding: 3 },
      headStyles: { fillColor: [27, 42, 110] },
    });
    const pageHeight = doc.internal.pageSize.getHeight();
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text('Generated by Erip Technologies · 0710951879', 14, pageHeight - 10);

    doc.save(`employee-report-${new Date().toISOString().slice(0, 10)}.pdf`);
  }

  function exportExcel() {
    const worksheet = XLSX.utils.json_to_sheet(
      filtered.map((e) => ({
        'Employee #': e.employee_number ?? '—',
        Name: `${e.user.first_name} ${e.user.last_name}`,
        Email: e.user.email,
        Phone: e.user.phone_number || '—',
        Role: e.user.role ?? '—',
        Status: e.employment_status,
        'Date Employed': e.date_employed,
      }))
    );
    const workbook = XLSX.utils.book_new();
    workbook.Props = { Author: 'Erip Technologies', Company: 'Crimecurb Security Services' };
    XLSX.utils.book_append_sheet(workbook, worksheet, 'Employees');
    XLSX.writeFile(workbook, `employee-report-${new Date().toISOString().slice(0, 10)}.xlsx`);
  }

  return (
    <div>
      <Link to="/reports" className="inline-flex items-center gap-1 text-sm text-slate-500 hover:text-slate-700 mb-4 print:hidden">
        <ArrowLeft size={14} /> Back to Reports
      </Link>

      <div className="flex items-start justify-between flex-wrap gap-3 mb-6">
        <div>
          <p className="text-[11px] font-mono font-semibold uppercase tracking-[2px] text-crimecurb-red mb-1">
            Human Resources · Reports
          </p>
          <h1 className="font-display text-2xl font-bold text-slate-800">Employee Report</h1>
        </div>
        <div className="flex gap-2 print:hidden">
          <button onClick={exportPDF} className="flex items-center gap-1.5 bg-white border border-slate-200 hover:border-slate-300 text-slate-700 text-sm font-medium px-3 py-2 rounded-lg transition-colors">
            <Download size={14} /> PDF
          </button>
          <button onClick={exportExcel} className="flex items-center gap-1.5 bg-white border border-slate-200 hover:border-slate-300 text-slate-700 text-sm font-medium px-3 py-2 rounded-lg transition-colors">
            <FileSpreadsheet size={14} /> Excel
          </button>
          <button onClick={() => window.print()} className="flex items-center gap-1.5 bg-crimecurb-navy hover:opacity-90 text-white text-sm font-medium px-3 py-2 rounded-lg transition-colors">
            <Printer size={14} /> Print
          </button>
        </div>
      </div>

      <div className="bg-white rounded-xl border border-slate-200 p-4 mb-6 grid grid-cols-1 sm:grid-cols-2 gap-3 print:hidden">
        <div>
          <label className="block text-xs text-slate-500 mb-1">Status</label>
          <select value={statusFilter} onChange={(e) => setStatusFilter(e.target.value)} className="w-full px-3 py-2 rounded border border-slate-300 text-sm">
            <option value="">All Statuses</option>
            {STATUSES.map((s) => <option key={s} value={s}>{s}</option>)}
          </select>
        </div>
        <div>
          <label className="block text-xs text-slate-500 mb-1">Role</label>
          <select value={roleFilter} onChange={(e) => setRoleFilter(e.target.value)} className="w-full px-3 py-2 rounded border border-slate-300 text-sm">
            <option value="">All Roles</option>
            {ROLES.map((r) => <option key={r} value={r}>{r}</option>)}
          </select>
        </div>
      </div>

      {isLoading && <p className="text-slate-500">Loading...</p>}
      {error && <p className="text-red-600">{error}</p>}

      {!isLoading && !error && (
        <>
          <div className="grid grid-cols-2 lg:grid-cols-4 gap-3.5 mb-6">
            <div className="bg-white rounded-xl border border-slate-200 p-4">
              <p className="text-[10.5px] font-semibold uppercase tracking-wide text-slate-500 mb-1">Total Employees</p>
              <p className="font-mono text-2xl font-bold text-slate-800">{summary.total}</p>
            </div>
            <div className="bg-white rounded-xl border border-slate-200 p-4">
              <p className="text-[10.5px] font-semibold uppercase tracking-wide text-slate-500 mb-1">Active</p>
              <p className="font-mono text-2xl font-bold text-slate-800">{summary.active}</p>
            </div>
            <div className="bg-white rounded-xl border border-slate-200 p-4">
              <p className="text-[10.5px] font-semibold uppercase tracking-wide text-slate-500 mb-1">Guards</p>
              <p className="font-mono text-2xl font-bold text-slate-800">{summary.guards}</p>
            </div>
            <div className="bg-white rounded-xl border border-slate-200 p-4">
              <p className="text-[10.5px] font-semibold uppercase tracking-wide text-slate-500 mb-1">Management</p>
              <p className="font-mono text-2xl font-bold text-slate-800">{summary.management}</p>
            </div>
          </div>

          {chartData.length > 0 && (
            <div className="bg-white rounded-xl border border-slate-200 p-4 mb-6">
              <p className="text-xs font-semibold uppercase tracking-wide text-slate-500 mb-4">Headcount by Role</p>
              <div className="flex items-end gap-3 h-32">
                {chartData.map(([role, count]) => (
                  <div key={role} className="flex-1 flex flex-col items-center gap-1">
                    <div className="w-full bg-crimecurb-navy rounded-t" style={{ height: `${(count / maxCount) * 100}%`, minHeight: '4px' }} title={`${role}: ${count}`} />
                    <p className="text-[9px] text-slate-400 whitespace-nowrap mt-1">{role}</p>
                  </div>
                ))}
              </div>
            </div>
          )}

          <div className="bg-white rounded-xl border border-slate-200 overflow-x-auto">
            <table className="w-full text-sm text-left whitespace-nowrap">
              <thead className="bg-slate-50 text-slate-500 uppercase text-xs">
                <tr>
                  <th className="px-4 py-3">Employee #</th>
                  <th className="px-4 py-3">Name</th>
                  <th className="px-4 py-3">Email</th>
                  <th className="px-4 py-3">Role</th>
                  <th className="px-4 py-3">Status</th>
                  <th className="px-4 py-3">Date Employed</th>
                </tr>
              </thead>
              <tbody>
                {filtered.map((e) => (
                  <tr key={e.id} className="border-t border-slate-100">
                    <td className="px-4 py-3 font-medium text-slate-800">{e.employee_number ?? '—'}</td>
                    <td className="px-4 py-3 text-slate-600">{e.user.first_name} {e.user.last_name}</td>
                    <td className="px-4 py-3 text-slate-600">{e.user.email}</td>
                    <td className="px-4 py-3 text-slate-600">{e.user.role ?? '—'}</td>
                    <td className="px-4 py-3">
                      <span className={`px-2 py-1 rounded text-xs font-medium ${e.employment_status === 'ACTIVE' ? 'bg-emerald-100 text-emerald-700' : 'bg-slate-100 text-slate-600'}`}>
                        {e.employment_status}
                      </span>
                    </td>
                    <td className="px-4 py-3 text-slate-600">{e.date_employed}</td>
                  </tr>
                ))}
                {filtered.length === 0 && (
                  <tr><td colSpan={6} className="px-4 py-6 text-center text-slate-400">No employees match these filters.</td></tr>
                )}
              </tbody>
            </table>
          </div>

          <div className="text-center text-xs text-slate-400 mt-8 pt-4 border-t border-slate-200">
            <p>Generated by Erip <span className="text-crimecurb-red font-semibold">⚡</span> Technologies</p>
            <p>0710951879</p>
          </div>
        </>
      )}
    </div>
  );
}