import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, Download, FileSpreadsheet, Printer } from 'lucide-react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';
import { getExpenses } from '../../api/expensesApi';
import type { Expense } from '../../types/expenses';

function formatKES(value: number): string {
  return new Intl.NumberFormat('en-KE', { style: 'currency', currency: 'KES' }).format(value);
}

const CATEGORIES = ['FUEL', 'EQUIPMENT', 'VEHICLE_MAINTENANCE', 'RENT_UTILITIES', 'LICENSES', 'OTHER'];

export default function ExpenseReportPage() {
  const [expenses, setExpenses] = useState<Expense[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [categoryFilter, setCategoryFilter] = useState('');
  const [startDate, setStartDate] = useState('');
  const [endDate, setEndDate] = useState('');

  useEffect(() => {
    getExpenses()
      .then(setExpenses)
      .catch((err) => {
        console.error(err);
        setError('Failed to load expense data.');
      })
      .finally(() => setIsLoading(false));
  }, []);

  const filtered = useMemo(() => {
    return expenses.filter((e) => {
      if (categoryFilter && e.category !== categoryFilter) return false;
      if (startDate && e.expense_date < startDate) return false;
      if (endDate && e.expense_date > endDate) return false;
      return true;
    });
  }, [expenses, categoryFilter, startDate, endDate]);

  const summary = useMemo(() => {
    const total = filtered.reduce((sum, e) => sum + parseFloat(e.amount), 0);
    const pending = filtered.filter((e) => e.status === 'PENDING').reduce((sum, e) => sum + parseFloat(e.amount), 0);
    const overdue = filtered.filter((e) => e.status === 'OVERDUE').length;
    return { total, pending, overdue, count: filtered.length };
  }, [filtered]);

  const byCategory = useMemo(() => {
    const map: Record<string, number> = {};
    filtered.forEach((e) => {
      map[e.category] = (map[e.category] ?? 0) + parseFloat(e.amount);
    });
    return Object.entries(map).sort(([, a], [, b]) => b - a);
  }, [filtered]);

  const maxCategoryValue = Math.max(1, ...byCategory.map(([, v]) => v));

  function exportPDF() {
    const doc = new jsPDF({ orientation: 'landscape' });
    doc.setFontSize(16);
    doc.text('Expense Report', 14, 16);
    doc.setFontSize(10);
    doc.text(`Generated: ${new Date().toLocaleDateString('en-KE')}`, 14, 23);

    autoTable(doc, {
      startY: 30,
      head: [['Description', 'Category', 'Vendor', 'Amount', 'Expense Date', 'Status']],
      body: filtered.map((e) => [
        e.description,
        e.category.replace('_', ' '),
        e.vendor_name || '—',
        formatKES(parseFloat(e.amount)),
        e.expense_date,
        e.status,
      ]),
      styles: { fontSize: 9, cellPadding: 3 },
      headStyles: { fillColor: [27, 42, 110] },
    });

    const pageHeight = doc.internal.pageSize.getHeight();
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text('Generated by Erip Technologies · 0710951879', 14, pageHeight - 10);

    doc.save(`expense-report-${new Date().toISOString().slice(0, 10)}.pdf`);
  }

  function exportExcel() {
    const worksheet = XLSX.utils.json_to_sheet(
      filtered.map((e) => ({
        Description: e.description,
        Category: e.category.replace('_', ' '),
        Vendor: e.vendor_name || '—',
        Amount: parseFloat(e.amount),
        'Expense Date': e.expense_date,
        Status: e.status,
      }))
    );
    const workbook = XLSX.utils.book_new();
    workbook.Props = { Author: 'Erip Technologies', Company: 'Crimecurb Security Services' };
    XLSX.utils.book_append_sheet(workbook, worksheet, 'Expenses');
    XLSX.writeFile(workbook, `expense-report-${new Date().toISOString().slice(0, 10)}.xlsx`);
  }

  return (
    <div>
      <Link to="/reports" className="inline-flex items-center gap-1 text-sm text-slate-500 hover:text-slate-700 mb-4 print:hidden">
        <ArrowLeft size={14} /> Back to Reports
      </Link>

      <div className="flex items-start justify-between flex-wrap gap-3 mb-6">
        <div>
          <p className="text-[11px] font-mono font-semibold uppercase tracking-[2px] text-crimecurb-red mb-1">
            Financial · Reports
          </p>
          <h1 className="font-display text-2xl font-bold text-slate-800">Expense Report</h1>
        </div>
        <div className="flex gap-2 print:hidden">
          <button onClick={exportPDF} className="flex items-center gap-1.5 bg-white border border-slate-200 hover:border-slate-300 text-slate-700 text-sm font-medium px-3 py-2 rounded-lg transition-colors">
            <Download size={14} /> PDF
          </button>
          <button onClick={exportExcel} className="flex items-center gap-1.5 bg-white border border-slate-200 hover:border-slate-300 text-slate-700 text-sm font-medium px-3 py-2 rounded-lg transition-colors">
            <FileSpreadsheet size={14} /> Excel
          </button>
          <button onClick={() => window.print()} className="flex items-center gap-1.5 bg-crimecurb-navy hover:opacity-90 text-white text-sm font-medium px-3 py-2 rounded-lg transition-colors">
            <Printer size={14} /> Print
          </button>
        </div>
      </div>

      {/* Filters */}
      <div className="bg-white rounded-xl border border-slate-200 p-4 mb-6 grid grid-cols-1 sm:grid-cols-3 gap-3 print:hidden">
        <div>
          <label className="block text-xs text-slate-500 mb-1">Category</label>
          <select
            value={categoryFilter}
            onChange={(e) => setCategoryFilter(e.target.value)}
            className="w-full px-3 py-2 rounded border border-slate-300 text-sm"
          >
            <option value="">All Categories</option>
            {CATEGORIES.map((c) => (
              <option key={c} value={c}>{c.replace('_', ' ')}</option>
            ))}
          </select>
        </div>
        <div>
          <label className="block text-xs text-slate-500 mb-1">Start Date</label>
          <input
            type="date"
            value={startDate}
            onChange={(e) => setStartDate(e.target.value)}
            className="w-full px-3 py-2 rounded border border-slate-300 text-sm"
          />
        </div>
        <div>
          <label className="block text-xs text-slate-500 mb-1">End Date</label>
          <input
            type="date"
            value={endDate}
            onChange={(e) => setEndDate(e.target.value)}
            className="w-full px-3 py-2 rounded border border-slate-300 text-sm"
          />
        </div>
      </div>

      {isLoading && <p className="text-slate-500">Loading...</p>}
      {error && <p className="text-red-600">{error}</p>}

      {!isLoading && !error && (
        <>
          <div className="grid grid-cols-2 lg:grid-cols-4 gap-3.5 mb-6">
            <div className="bg-white rounded-xl border border-slate-200 p-4">
              <p className="text-[10.5px] font-semibold uppercase tracking-wide text-slate-500 mb-1">Total Expenses</p>
              <p className="font-mono text-2xl font-bold text-slate-800">{summary.count}</p>
            </div>
            <div className="bg-white rounded-xl border border-slate-200 p-4">
              <p className="text-[10.5px] font-semibold uppercase tracking-wide text-slate-500 mb-1">Total Amount</p>
              <p className="font-mono text-2xl font-bold text-slate-800">{formatKES(summary.total)}</p>
            </div>
            <div className="bg-white rounded-xl border border-slate-200 p-4">
              <p className="text-[10.5px] font-semibold uppercase tracking-wide text-slate-500 mb-1">Pending Payment</p>
              <p className="font-mono text-2xl font-bold text-slate-800">{formatKES(summary.pending)}</p>
            </div>
            <div className="bg-white rounded-xl border border-slate-200 p-4">
              <p className="text-[10.5px] font-semibold uppercase tracking-wide text-slate-500 mb-1">Overdue</p>
              <p className={`font-mono text-2xl font-bold ${summary.overdue > 0 ? 'text-red-600' : 'text-slate-800'}`}>
                {summary.overdue}
              </p>
            </div>
          </div>

          {byCategory.length > 0 && (
            <div className="bg-white rounded-xl border border-slate-200 p-4 mb-6">
              <p className="text-xs font-semibold uppercase tracking-wide text-slate-500 mb-4">By Category</p>
              <div className="space-y-2">
                {byCategory.map(([cat, total]) => (
                  <div key={cat} className="flex items-center gap-3">
                    <p className="text-xs text-slate-600 w-40 shrink-0">{cat.replace('_', ' ')}</p>
                    <div className="flex-1 bg-slate-100 rounded-full h-3 overflow-hidden">
                      <div
                        className="h-full bg-crimecurb-navy rounded-full"
                        style={{ width: `${(total / maxCategoryValue) * 100}%` }}
                      />
                    </div>
                    <p className="text-xs font-medium text-slate-800 w-24 text-right shrink-0">{formatKES(total)}</p>
                  </div>
                ))}
              </div>
            </div>
          )}

          <div className="bg-white rounded-xl border border-slate-200 overflow-hidden">
            <table className="w-full text-sm text-left">
              <thead className="bg-slate-50 text-slate-500 uppercase text-xs">
                <tr>
                  <th className="px-4 py-3">Description</th>
                  <th className="px-4 py-3">Category</th>
                  <th className="px-4 py-3">Vendor</th>
                  <th className="px-4 py-3">Amount</th>
                  <th className="px-4 py-3">Expense Date</th>
                  <th className="px-4 py-3">Status</th>
                </tr>
              </thead>
              <tbody>
                {filtered.map((e) => (
                  <tr key={e.id} className="border-t border-slate-100">
                    <td className="px-4 py-3 font-medium text-slate-800">{e.description}</td>
                    <td className="px-4 py-3 text-slate-600">{e.category.replace('_', ' ')}</td>
                    <td className="px-4 py-3 text-slate-600">{e.vendor_name || '—'}</td>
                    <td className="px-4 py-3 text-slate-800">{formatKES(parseFloat(e.amount))}</td>
                    <td className="px-4 py-3 text-slate-600">{e.expense_date}</td>
                    <td className="px-4 py-3 text-slate-600">{e.status}</td>
                  </tr>
                ))}
                {filtered.length === 0 && (
                  <tr>
                    <td colSpan={6} className="px-4 py-6 text-center text-slate-400">
                      No expenses match these filters.
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>

          <div className="text-center text-xs text-slate-400 mt-8 pt-4 border-t border-slate-200">
            <p>Generated by Erip <span className="text-crimecurb-red font-semibold">⚡</span> Technologies</p>
            <p>0710951879</p>
          </div>
        </>
      )}
    </div>
  );
}