import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, Download, FileSpreadsheet, Printer } from 'lucide-react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';
import { getSiteAssignments, getSites } from '../../api/sitesApi';
import { getEmployeeProfiles } from '../../api/staffApi';
import type { SiteAssignment, Site } from '../../types/sites';
import type { EmployeeProfile } from '../../types/staff';

export default function GuardDeploymentReportPage() {
  const [assignments, setAssignments] = useState<SiteAssignment[]>([]);
  const [sites, setSites] = useState<Site[]>([]);
  const [employees, setEmployees] = useState<EmployeeProfile[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const [siteFilter, setSiteFilter] = useState('');
  const [statusFilter, setStatusFilter] = useState<'ALL' | 'DEPLOYED' | 'UNASSIGNED'>('ALL');

  useEffect(() => {
    Promise.all([getSiteAssignments(), getSites(), getEmployeeProfiles()])
      .then(([a, s, e]) => {
        setAssignments(a);
        setSites(s);
        setEmployees(e);
      })
      .catch((err) => {
        console.error(err);
        setError('Failed to load deployment data.');
      })
      .finally(() => setIsLoading(false));
  }, []);

  const today = new Date().toISOString().slice(0, 10);

  const currentAssignmentByEmployee = useMemo(() => {
    const map: Record<string, SiteAssignment> = {};
    assignments
      .filter((a) => a.is_active && (!a.end_date || a.end_date >= today))
      .forEach((a) => {
        const existing = map[a.employee];
        if (!existing || a.start_date > existing.start_date) map[a.employee] = a;
      });
    return map;
  }, [assignments, today]);

  const rows = useMemo(() => {
    return employees
      .filter((e) => e.user.role === 'GUARD')
      .map((e) => {
        const assignment = currentAssignmentByEmployee[e.id];
        return {
          id: e.id,
          name: `${e.user.first_name} ${e.user.last_name}`,
          employeeNumber: e.employee_number,
          status: e.employment_status,
          siteName: assignment?.site_name ?? null,
          startDate: assignment?.start_date ?? null,
        };
      })
      .filter((r) => {
        if (siteFilter && r.siteName !== siteFilter) return false;
        if (statusFilter === 'DEPLOYED' && !r.siteName) return false;
        if (statusFilter === 'UNASSIGNED' && r.siteName) return false;
        return true;
      });
  }, [employees, currentAssignmentByEmployee, siteFilter, statusFilter]);

  const summary = useMemo(() => {
    const total = rows.length;
    const deployed = rows.filter((r) => r.siteName).length;
    return { total, deployed, unassigned: total - deployed };
  }, [rows]);

  function exportPDF() {
    const doc = new jsPDF({ orientation: 'landscape' });
    doc.setFontSize(16);
    doc.text('Guard Deployment Report', 14, 16);
    doc.setFontSize(10);
    doc.text(`Generated: ${new Date().toLocaleDateString('en-KE')}`, 14, 23);

    autoTable(doc, {
      startY: 32,
      head: [['Employee #', 'Guard', 'Employment Status', 'Site', 'Deployed Since']],
      body: rows.map((r) => [
        r.employeeNumber, r.name, r.status, r.siteName ?? 'Unassigned', r.startDate ?? '—',
      ]),
      styles: { fontSize: 9, cellPadding: 3 },
      headStyles: { fillColor: [27, 42, 110] },
    });

    const pageHeight = doc.internal.pageSize.getHeight();
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text('Generated by Erip Technologies · 0710951879', 14, pageHeight - 10);
    doc.save(`guard-deployment-report-${new Date().toISOString().slice(0, 10)}.pdf`);
  }

  function exportExcel() {
    const worksheet = XLSX.utils.json_to_sheet(
      rows.map((r) => ({
        'Employee #': r.employeeNumber, Guard: r.name, 'Employment Status': r.status,
        Site: r.siteName ?? 'Unassigned', 'Deployed Since': r.startDate ?? '',
      }))
    );
    const workbook = XLSX.utils.book_new();
    workbook.Props = { Author: 'Erip Technologies', Company: 'Crimecurb Security Services' };
    XLSX.utils.book_append_sheet(workbook, worksheet, 'Deployment');
    XLSX.writeFile(workbook, `guard-deployment-report-${new Date().toISOString().slice(0, 10)}.xlsx`);
  }

  return (
    <div>
      <Link to="/reports" className="inline-flex items-center gap-1 text-sm text-slate-500 hover:text-slate-700 mb-4 print:hidden">
        <ArrowLeft size={14} /> Back to Reports
      </Link>

      <div className="flex items-start justify-between flex-wrap gap-3 mb-6">
        <div>
          <p className="text-[11px] font-mono font-semibold uppercase tracking-[2px] text-crimecurb-red mb-1">
            Operational · Reports
          </p>
          <h1 className="font-display text-2xl font-bold text-slate-800">Guard Deployment Report</h1>
        </div>
        <div className="flex gap-2 print:hidden">
          <button onClick={exportPDF} className="flex items-center gap-1.5 bg-white border border-slate-200 hover:border-slate-300 text-slate-700 text-sm font-medium px-3 py-2 rounded-lg transition-colors">
            <Download size={14} /> PDF
          </button>
          <button onClick={exportExcel} className="flex items-center gap-1.5 bg-white border border-slate-200 hover:border-slate-300 text-slate-700 text-sm font-medium px-3 py-2 rounded-lg transition-colors">
            <FileSpreadsheet size={14} /> Excel
          </button>
          <button onClick={() => window.print()} className="flex items-center gap-1.5 bg-crimecurb-navy hover:opacity-90 text-white text-sm font-medium px-3 py-2 rounded-lg transition-colors">
            <Printer size={14} /> Print
          </button>
        </div>
      </div>

      <div className="bg-white rounded-xl border border-slate-200 p-4 mb-6 grid grid-cols-1 sm:grid-cols-2 gap-3 print:hidden">
        <div>
          <label className="block text-xs text-slate-500 mb-1">Site</label>
          <select value={siteFilter} onChange={(e) => setSiteFilter(e.target.value)} className="w-full px-3 py-2 rounded border border-slate-300 text-sm">
            <option value="">All Sites</option>
            {sites.map((s) => <option key={s.id} value={s.name}>{s.name}</option>)}
          </select>
        </div>
        <div>
          <label className="block text-xs text-slate-500 mb-1">Status</label>
          <select value={statusFilter} onChange={(e) => setStatusFilter(e.target.value as any)} className="w-full px-3 py-2 rounded border border-slate-300 text-sm">
            <option value="ALL">All</option>
            <option value="DEPLOYED">Deployed</option>
            <option value="UNASSIGNED">Unassigned</option>
          </select>
        </div>
      </div>

      {isLoading && <p className="text-slate-500">Loading...</p>}
      {error && <p className="text-red-600">{error}</p>}

      {!isLoading && !error && (
        <>
          <div className="grid grid-cols-3 gap-3.5 mb-6">
            <div className="bg-white rounded-xl border border-slate-200 p-4">
              <p className="text-[10.5px] font-semibold uppercase tracking-wide text-slate-500 mb-1">Total Guards</p>
              <p className="font-mono text-2xl font-bold text-slate-800">{summary.total}</p>
            </div>
            <div className="bg-white rounded-xl border border-slate-200 p-4">
              <p className="text-[10.5px] font-semibold uppercase tracking-wide text-slate-500 mb-1">Deployed</p>
              <p className="font-mono text-2xl font-bold text-emerald-700">{summary.deployed}</p>
            </div>
            <div className="bg-white rounded-xl border border-slate-200 p-4">
              <p className="text-[10.5px] font-semibold uppercase tracking-wide text-slate-500 mb-1">Unassigned</p>
              <p className="font-mono text-2xl font-bold text-red-700">{summary.unassigned}</p>
            </div>
          </div>

          <div className="bg-white rounded-xl border border-slate-200 overflow-hidden">
            <table className="w-full text-sm text-left">
              <thead className="bg-slate-50 text-slate-500 uppercase text-xs">
                <tr>
                  <th className="px-4 py-3">Employee #</th>
                  <th className="px-4 py-3">Guard</th>
                  <th className="px-4 py-3">Status</th>
                  <th className="px-4 py-3">Site</th>
                  <th className="px-4 py-3">Deployed Since</th>
                </tr>
              </thead>
              <tbody>
                {rows.map((r) => (
                  <tr key={r.id} className="border-t border-slate-100">
                    <td className="px-4 py-3 font-medium text-slate-800">{r.employeeNumber}</td>
                    <td className="px-4 py-3 text-slate-600">{r.name}</td>
                    <td className="px-4 py-3 text-slate-600">{r.status}</td>
                    <td className="px-4 py-3">
                      <span className={`px-2 py-1 rounded text-xs font-medium ${r.siteName ? 'bg-emerald-100 text-emerald-700' : 'bg-slate-100 text-slate-500'}`}>
                        {r.siteName ?? 'Unassigned'}
                      </span>
                    </td>
                    <td className="px-4 py-3 text-slate-600">{r.startDate ?? '—'}</td>
                  </tr>
                ))}
                {rows.length === 0 && (
                  <tr><td colSpan={5} className="px-4 py-6 text-center text-slate-400">No guards match these filters.</td></tr>
                )}
              </tbody>
            </table>
          </div>

          <div className="text-center text-xs text-slate-400 mt-8 pt-4 border-t border-slate-200">
            <p>Generated by Erip <span className="text-crimecurb-red font-semibold">⚡</span> Technologies</p>
            <p>0710951879</p>
          </div>
        </>
      )}
    </div>
  );
}