import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, Download, FileSpreadsheet, Printer } from 'lucide-react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';
import { getMyIncidents } from '../../api/incidentsApi';
import { getSites } from '../../api/sitesApi';
import type { Incident } from '../../types/incidents';
import type { Site } from '../../types/sites';

function hoursBetween(a: string, b: string): number {
  const diff = new Date(b).getTime() - new Date(a).getTime();
  return diff > 0 ? diff / (1000 * 60 * 60) : 0;
}

export default function IncidentResolutionReportPage() {
  const [incidents, setIncidents] = useState<Incident[]>([]);
  const [sites, setSites] = useState<Site[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const [startDate, setStartDate] = useState('');
  const [endDate, setEndDate] = useState('');
  const [siteFilter, setSiteFilter] = useState('');

  useEffect(() => {
    Promise.all([getMyIncidents(), getSites()])
      .then(([i, s]) => {
        setIncidents(i);
        setSites(s);
      })
      .catch((err) => {
        console.error(err);
        setError('Failed to load incident data.');
      })
      .finally(() => setIsLoading(false));
  }, []);

  const resolvedRows = useMemo(() => {
    return incidents
      .filter((i) => i.status === 'RESOLVED' || i.status === 'CLOSED')
      .filter((i) => {
        const occurredDate = i.occurred_at.slice(0, 10);
        if (startDate && occurredDate < startDate) return false;
        if (endDate && occurredDate > endDate) return false;
        if (siteFilter && i.site_name !== siteFilter) return false;
        return true;
      })
      .map((i) => ({
        ...i,
        // updated_at is a proxy for "when it was last changed" — the closest
        // signal we have to a resolution timestamp without a dedicated field.
        resolutionHours: hoursBetween(i.occurred_at, i.updated_at),
      }))
      .sort((a, b) => b.resolutionHours - a.resolutionHours);
  }, [incidents, startDate, endDate, siteFilter]);

  const summary = useMemo(() => {
    const total = resolvedRows.length;
    const avgHours = total > 0 ? resolvedRows.reduce((sum, r) => sum + r.resolutionHours, 0) / total : 0;
    const under24h = resolvedRows.filter((r) => r.resolutionHours <= 24).length;
    const over72h = resolvedRows.filter((r) => r.resolutionHours > 72).length;
    return { total, avgHours: avgHours.toFixed(1), under24h, over72h };
  }, [resolvedRows]);

  function exportPDF() {
    const doc = new jsPDF({ orientation: 'landscape' });
    doc.setFontSize(16);
    doc.text('Incident Resolution Report', 14, 16);
    doc.setFontSize(9);
    doc.text('Resolution time is estimated from last status update, not a dedicated resolved-at field.', 14, 22);
    doc.setFontSize(10);
    doc.text(`Generated: ${new Date().toLocaleDateString('en-KE')}`, 14, 29);

    autoTable(doc, {
      startY: 36,
      head: [['Title', 'Site', 'Severity', 'Occurred', 'Last Updated', 'Hours to Resolve', 'Status']],
      body: resolvedRows.map((r) => [
        r.title, r.site_name, r.severity,
        r.occurred_at.slice(0, 10), r.updated_at.slice(0, 10),
        r.resolutionHours.toFixed(1), r.status,
      ]),
      styles: { fontSize: 8, cellPadding: 3 },
      headStyles: { fillColor: [27, 42, 110] },
    });

    const pageHeight = doc.internal.pageSize.getHeight();
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text('Generated by Erip Technologies · 0710951879', 14, pageHeight - 10);
    doc.save(`incident-resolution-report-${new Date().toISOString().slice(0, 10)}.pdf`);
  }

  function exportExcel() {
    const worksheet = XLSX.utils.json_to_sheet(
      resolvedRows.map((r) => ({
        Title: r.title, Site: r.site_name, Severity: r.severity,
        Occurred: r.occurred_at.slice(0, 10), 'Last Updated': r.updated_at.slice(0, 10),
        'Hours to Resolve': r.resolutionHours.toFixed(1), Status: r.status,
      }))
    );
    const workbook = XLSX.utils.book_new();
    workbook.Props = { Author: 'Erip Technologies', Company: 'Crimecurb Security Services' };
    XLSX.utils.book_append_sheet(workbook, worksheet, 'Resolution');
    XLSX.writeFile(workbook, `incident-resolution-report-${new Date().toISOString().slice(0, 10)}.xlsx`);
  }

  return (
    <div>
      <Link to="/reports" className="inline-flex items-center gap-1 text-sm text-slate-500 hover:text-slate-700 mb-4 print:hidden">
        <ArrowLeft size={14} /> Back to Reports
      </Link>

      <div className="flex items-start justify-between flex-wrap gap-3 mb-2">
        <div>
          <p className="text-[11px] font-mono font-semibold uppercase tracking-[2px] text-crimecurb-red mb-1">
            Operational · Reports
          </p>
          <h1 className="font-display text-2xl font-bold text-slate-800">Incident Resolution Report</h1>
        </div>
        <div className="flex gap-2 print:hidden">
          <button onClick={exportPDF} className="flex items-center gap-1.5 bg-white border border-slate-200 hover:border-slate-300 text-slate-700 text-sm font-medium px-3 py-2 rounded-lg transition-colors">
            <Download size={14} /> PDF
          </button>
          <button onClick={exportExcel} className="flex items-center gap-1.5 bg-white border border-slate-200 hover:border-slate-300 text-slate-700 text-sm font-medium px-3 py-2 rounded-lg transition-colors">
            <FileSpreadsheet size={14} /> Excel
          </button>
          <button onClick={() => window.print()} className="flex items-center gap-1.5 bg-crimecurb-navy hover:opacity-90 text-white text-sm font-medium px-3 py-2 rounded-lg transition-colors">
            <Printer size={14} /> Print
          </button>
        </div>
      </div>
      <p className="text-xs text-slate-400 mb-6 print:hidden">
        Resolution time is estimated from each incident's last status update — not a dedicated resolved-at field.
      </p>

      <div className="bg-white rounded-xl border border-slate-200 p-4 mb-6 grid grid-cols-1 sm:grid-cols-3 gap-3 print:hidden">
        <div>
          <label className="block text-xs text-slate-500 mb-1">Start Date</label>
          <input type="date" value={startDate} onChange={(e) => setStartDate(e.target.value)} className="w-full px-3 py-2 rounded border border-slate-300 text-sm" />
        </div>
        <div>
          <label className="block text-xs text-slate-500 mb-1">End Date</label>
          <input type="date" value={endDate} onChange={(e) => setEndDate(e.target.value)} className="w-full px-3 py-2 rounded border border-slate-300 text-sm" />
        </div>
        <div>
          <label className="block text-xs text-slate-500 mb-1">Site</label>
          <select value={siteFilter} onChange={(e) => setSiteFilter(e.target.value)} className="w-full px-3 py-2 rounded border border-slate-300 text-sm">
            <option value="">All Sites</option>
            {sites.map((s) => <option key={s.id} value={s.name}>{s.name}</option>)}
          </select>
        </div>
      </div>

      {isLoading && <p className="text-slate-500">Loading...</p>}
      {error && <p className="text-red-600">{error}</p>}

      {!isLoading && !error && (
        <>
          <div className="grid grid-cols-2 lg:grid-cols-4 gap-3.5 mb-6">
            <div className="bg-white rounded-xl border border-slate-200 p-4">
              <p className="text-[10.5px] font-semibold uppercase tracking-wide text-slate-500 mb-1">Resolved Incidents</p>
              <p className="font-mono text-2xl font-bold text-slate-800">{summary.total}</p>
            </div>
            <div className="bg-white rounded-xl border border-slate-200 p-4">
              <p className="text-[10.5px] font-semibold uppercase tracking-wide text-slate-500 mb-1">Avg. Hours to Resolve</p>
              <p className="font-mono text-2xl font-bold text-slate-800">{summary.avgHours}</p>
            </div>
            <div className="bg-white rounded-xl border border-slate-200 p-4">
              <p className="text-[10.5px] font-semibold uppercase tracking-wide text-slate-500 mb-1">Resolved Under 24h</p>
              <p className="font-mono text-2xl font-bold text-emerald-700">{summary.under24h}</p>
            </div>
            <div className="bg-white rounded-xl border border-slate-200 p-4">
              <p className="text-[10.5px] font-semibold uppercase tracking-wide text-slate-500 mb-1">Over 72h</p>
              <p className="font-mono text-2xl font-bold text-red-700">{summary.over72h}</p>
            </div>
          </div>

          <div className="bg-white rounded-xl border border-slate-200 overflow-hidden">
            <table className="w-full text-sm text-left">
              <thead className="bg-slate-50 text-slate-500 uppercase text-xs">
                <tr>
                  <th className="px-4 py-3">Title</th>
                  <th className="px-4 py-3">Site</th>
                  <th className="px-4 py-3">Severity</th>
                  <th className="px-4 py-3">Occurred</th>
                  <th className="px-4 py-3">Last Updated</th>
                  <th className="px-4 py-3">Hours to Resolve</th>
                  <th className="px-4 py-3">Status</th>
                </tr>
              </thead>
              <tbody>
                {resolvedRows.map((r) => (
                  <tr key={r.id} className="border-t border-slate-100">
                    <td className="px-4 py-3 font-medium text-slate-800">{r.title}</td>
                    <td className="px-4 py-3 text-slate-600">{r.site_name}</td>
                    <td className="px-4 py-3 text-slate-600">{r.severity}</td>
                    <td className="px-4 py-3 text-slate-600">{r.occurred_at.slice(0, 10)}</td>
                    <td className="px-4 py-3 text-slate-600">{r.updated_at.slice(0, 10)}</td>
                    <td className="px-4 py-3 text-slate-600">{r.resolutionHours.toFixed(1)}</td>
                    <td className="px-4 py-3 text-slate-600">{r.status}</td>
                  </tr>
                ))}
                {resolvedRows.length === 0 && (
                  <tr><td colSpan={7} className="px-4 py-6 text-center text-slate-400">No resolved incidents in this range.</td></tr>
                )}
              </tbody>
            </table>
          </div>

          <div className="text-center text-xs text-slate-400 mt-8 pt-4 border-t border-slate-200">
            <p>Generated by Erip <span className="text-crimecurb-red font-semibold">⚡</span> Technologies</p>
            <p>0710951879</p>
          </div>
        </>
      )}
    </div>
  );
}