import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, Download, FileSpreadsheet, Printer } from 'lucide-react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';
import { getPayslips, getPayrollPeriods } from '../../api/payrollApi';
import type { Payslip, PayrollPeriod } from '../../types/payroll';

function formatKES(value: number): string {
  return new Intl.NumberFormat('en-KE', { style: 'currency', currency: 'KES' }).format(value);
}

export default function PayrollSummaryPage() {
  const [payslips, setPayslips] = useState<Payslip[]>([]);
  const [periods, setPeriods] = useState<PayrollPeriod[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    Promise.all([getPayslips(), getPayrollPeriods()])
      .then(([p, per]) => {
        setPayslips(p);
        setPeriods(per);
      })
      .catch((err) => {
        console.error(err);
        setError('Failed to load payroll summary data.');
      })
      .finally(() => setIsLoading(false));
  }, []);

  const periodRows = useMemo(() => {
    return periods
      .map((period) => {
        const slips = payslips.filter((p) => p.period === period.id);
        const employeeCount = slips.length;
        const totalGross = slips.reduce((sum, p) => sum + parseFloat(p.gross_pay), 0);
        const totalNssf = slips.reduce((sum, p) => sum + parseFloat(p.nssf_employee), 0);
        const totalShif = slips.reduce((sum, p) => sum + parseFloat(p.shif_contribution), 0);
        const totalHousing = slips.reduce((sum, p) => sum + parseFloat(p.housing_levy), 0);
        const totalPaye = slips.reduce((sum, p) => sum + parseFloat(p.paye_tax), 0);
        const totalOther = slips.reduce((sum, p) => sum + parseFloat(p.total_other_deductions), 0);
        const totalNet = slips.reduce((sum, p) => sum + parseFloat(p.net_pay), 0);
        const allPaid = employeeCount > 0 && slips.every((p) => p.status === 'PAID');
        const anyUnpaid = slips.some((p) => p.status !== 'PAID');

        return {
          period,
          employeeCount,
          totalGross,
          totalNssf,
          totalShif,
          totalHousing,
          totalPaye,
          totalOther,
          totalNet,
          payoutStatus: employeeCount === 0 ? 'No Payslips' : allPaid ? 'Fully Paid' : anyUnpaid ? 'Pending Payment' : 'Mixed',
        };
      })
      .sort((a, b) => b.period.period_start.localeCompare(a.period.period_start));
  }, [periods, payslips]);

  const overallSummary = useMemo(() => {
    const totalNet = periodRows.reduce((sum, r) => sum + r.totalNet, 0);
    const totalGross = periodRows.reduce((sum, r) => sum + r.totalGross, 0);
    const totalStatutory = periodRows.reduce(
      (sum, r) => sum + r.totalNssf + r.totalShif + r.totalHousing + r.totalPaye,
      0
    );
    const periodsWithData = periodRows.filter((r) => r.employeeCount > 0).length;
    return { totalNet, totalGross, totalStatutory, periodsWithData };
  }, [periodRows]);

  const chartData = periodRows
    .filter((r) => r.employeeCount > 0)
    .slice(0, 12)
    .reverse();
  const maxNet = Math.max(1, ...chartData.map((r) => r.totalNet));

  function periodLabel(p: PayrollPeriod) {
    return `${p.period_start} – ${p.period_end}`;
  }

  function exportPDF() {
    const doc = new jsPDF({ orientation: 'landscape' });
    doc.setFontSize(16);
    doc.text('Payroll Summary', 14, 16);
    doc.setFontSize(10);
    doc.text(`Generated: ${new Date().toLocaleDateString('en-KE')}`, 14, 23);

    autoTable(doc, {
      startY: 30,
      head: [['Period', 'Employees', 'Gross Pay', 'Statutory Deductions', 'Net Pay', 'Status']],
      body: periodRows.map((r) => [
        periodLabel(r.period),
        r.employeeCount,
        formatKES(r.totalGross),
        formatKES(r.totalNssf + r.totalShif + r.totalHousing + r.totalPaye),
        formatKES(r.totalNet),
        r.payoutStatus,
      ]),
      styles: { fontSize: 9, cellPadding: 3 },
      headStyles: { fillColor: [27, 42, 110] },
    });

    const pageHeight = doc.internal.pageSize.getHeight();
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text('Generated by Erip Technologies · 0710951879', 14, pageHeight - 10);

    doc.save(`payroll-summary-${new Date().toISOString().slice(0, 10)}.pdf`);
  }

  function exportExcel() {
    const worksheet = XLSX.utils.json_to_sheet(
      periodRows.map((r) => ({
        Period: periodLabel(r.period),
        Employees: r.employeeCount,
        'Gross Pay': r.totalGross,
        NSSF: r.totalNssf,
        SHIF: r.totalShif,
        'Housing Levy': r.totalHousing,
        PAYE: r.totalPaye,
        'Other Deductions': r.totalOther,
        'Net Pay': r.totalNet,
        Status: r.payoutStatus,
      }))
    );
    const workbook = XLSX.utils.book_new();
    workbook.Props = { Author: 'Erip Technologies', Company: 'Crimecurb Security Services' };
    XLSX.utils.book_append_sheet(workbook, worksheet, 'Payroll Summary');
    XLSX.writeFile(workbook, `payroll-summary-${new Date().toISOString().slice(0, 10)}.xlsx`);
  }

  return (
    <div>
      <Link to="/reports" className="inline-flex items-center gap-1 text-sm text-slate-500 hover:text-slate-700 mb-4 print:hidden">
        <ArrowLeft size={14} /> Back to Reports
      </Link>

      <div className="flex items-start justify-between flex-wrap gap-3 mb-6">
        <div>
          <p className="text-[11px] font-mono font-semibold uppercase tracking-[2px] text-crimecurb-red mb-1">
            Financial · Reports
          </p>
          <h1 className="font-display text-2xl font-bold text-slate-800">Payroll Summary</h1>
        </div>
        <div className="flex gap-2 print:hidden">
          <button onClick={exportPDF} className="flex items-center gap-1.5 bg-white border border-slate-200 hover:border-slate-300 text-slate-700 text-sm font-medium px-3 py-2 rounded-lg transition-colors">
            <Download size={14} /> PDF
          </button>
          <button onClick={exportExcel} className="flex items-center gap-1.5 bg-white border border-slate-200 hover:border-slate-300 text-slate-700 text-sm font-medium px-3 py-2 rounded-lg transition-colors">
            <FileSpreadsheet size={14} /> Excel
          </button>
          <button onClick={() => window.print()} className="flex items-center gap-1.5 bg-crimecurb-navy hover:opacity-90 text-white text-sm font-medium px-3 py-2 rounded-lg transition-colors">
            <Printer size={14} /> Print
          </button>
        </div>
      </div>

      {isLoading && <p className="text-slate-500">Loading...</p>}
      {error && <p className="text-red-600">{error}</p>}

      {!isLoading && !error && (
        <>
          <div className="grid grid-cols-2 lg:grid-cols-4 gap-3.5 mb-6">
            <div className="bg-white rounded-xl border border-slate-200 p-4">
              <p className="text-[10.5px] font-semibold uppercase tracking-wide text-slate-500 mb-1">Periods with Payroll</p>
              <p className="font-mono text-2xl font-bold text-slate-800">{overallSummary.periodsWithData}</p>
            </div>
            <div className="bg-white rounded-xl border border-slate-200 p-4">
              <p className="text-[10.5px] font-semibold uppercase tracking-wide text-slate-500 mb-1">Total Gross (All Time)</p>
              <p className="font-mono text-2xl font-bold text-slate-800">{formatKES(overallSummary.totalGross)}</p>
            </div>
            <div className="bg-white rounded-xl border border-slate-200 p-4">
              <p className="text-[10.5px] font-semibold uppercase tracking-wide text-slate-500 mb-1">Total Statutory (All Time)</p>
              <p className="font-mono text-2xl font-bold text-slate-800">{formatKES(overallSummary.totalStatutory)}</p>
            </div>
            <div className="bg-white rounded-xl border border-slate-200 p-4">
              <p className="text-[10.5px] font-semibold uppercase tracking-wide text-slate-500 mb-1">Total Net (All Time)</p>
              <p className="font-mono text-2xl font-bold text-slate-800">{formatKES(overallSummary.totalNet)}</p>
            </div>
          </div>

          {chartData.length > 0 && (
            <div className="bg-white rounded-xl border border-slate-200 p-4 mb-6">
              <p className="text-xs font-semibold uppercase tracking-wide text-slate-500 mb-4">
                Net Payroll by Period
              </p>
              <div className="flex items-end gap-2 h-32">
                {chartData.map((r) => (
                  <div key={r.period.id} className="flex-1 flex flex-col items-center gap-1">
                    <div
                      className="w-full bg-crimecurb-navy rounded-t"
                      style={{ height: `${(r.totalNet / maxNet) * 100}%`, minHeight: '4px' }}
                      title={`${periodLabel(r.period)}: ${formatKES(r.totalNet)}`}
                    />
                    <p className="text-[9px] text-slate-400 rotate-45 origin-left whitespace-nowrap mt-1">
                      {r.period.period_start.slice(5)}
                    </p>
                  </div>
                ))}
              </div>
            </div>
          )}

          <div className="bg-white rounded-xl border border-slate-200 overflow-hidden">
            <table className="w-full text-sm text-left">
              <thead className="bg-slate-50 text-slate-500 uppercase text-xs">
                <tr>
                  <th className="px-4 py-3">Period</th>
                  <th className="px-4 py-3">Employees</th>
                  <th className="px-4 py-3">Gross Pay</th>
                  <th className="px-4 py-3">Statutory Deductions</th>
                  <th className="px-4 py-3">Net Pay</th>
                  <th className="px-4 py-3">Status</th>
                </tr>
              </thead>
              <tbody>
                {periodRows.map((r) => (
                  <tr key={r.period.id} className="border-t border-slate-100">
                    <td className="px-4 py-3 font-medium text-slate-800">{periodLabel(r.period)}</td>
                    <td className="px-4 py-3 text-slate-600">{r.employeeCount}</td>
                    <td className="px-4 py-3 text-slate-600">{formatKES(r.totalGross)}</td>
                    <td className="px-4 py-3 text-slate-600">
                      {formatKES(r.totalNssf + r.totalShif + r.totalHousing + r.totalPaye)}
                    </td>
                    <td className="px-4 py-3 font-medium text-slate-800">{formatKES(r.totalNet)}</td>
                    <td className="px-4 py-3">
                      <span
                        className={`px-2 py-1 rounded text-xs font-medium ${
                          r.payoutStatus === 'Fully Paid'
                            ? 'bg-emerald-100 text-emerald-700'
                            : r.payoutStatus === 'Pending Payment'
                            ? 'bg-amber-100 text-amber-700'
                            : 'bg-slate-100 text-slate-500'
                        }`}
                      >
                        {r.payoutStatus}
                      </span>
                    </td>
                  </tr>
                ))}
                {periodRows.length === 0 && (
                  <tr>
                    <td colSpan={6} className="px-4 py-6 text-center text-slate-400">
                      No payroll periods found.
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>

          <div className="text-center text-xs text-slate-400 mt-8 pt-4 border-t border-slate-200">
            <p>Generated by Erip <span className="text-crimecurb-red font-semibold">⚡</span> Technologies</p>
            <p>0710951879</p>
          </div>
        </>
      )}
    </div>
  );
}