import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, Download, FileSpreadsheet, Printer } from 'lucide-react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';
import { getPayslips, getPayrollPeriods } from '../../api/payrollApi';
import { getEmployeeProfiles } from '../../api/staffApi';
import type { Payslip, PayrollPeriod } from '../../types/payroll';
import type { EmployeeProfile } from '../../types/staff';

function formatKES(value: number): string {
  return new Intl.NumberFormat('en-KE', { style: 'currency', currency: 'KES' }).format(value);
}

const STATUSES = ['DRAFT', 'APPROVED', 'PAID'];

export default function PayslipReportPage() {
  const [payslips, setPayslips] = useState<Payslip[]>([]);
  const [periods, setPeriods] = useState<PayrollPeriod[]>([]);
  const [employees, setEmployees] = useState<EmployeeProfile[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const [periodFilter, setPeriodFilter] = useState('');
  const [employeeFilter, setEmployeeFilter] = useState('');
  const [statusFilter, setStatusFilter] = useState('');

  useEffect(() => {
    Promise.all([getPayslips(), getPayrollPeriods(), getEmployeeProfiles()])
      .then(([p, per, e]) => {
        setPayslips(p);
        setPeriods(per);
        setEmployees(e);
      })
      .catch((err) => {
        console.error(err);
        setError('Failed to load payslip data.');
      })
      .finally(() => setIsLoading(false));
  }, []);

  const filtered = useMemo(() => {
    return payslips.filter((p) => {
      if (periodFilter && p.period !== periodFilter) return false;
      if (employeeFilter && p.employee_name !== employeeFilter) return false;
      if (statusFilter && p.status !== statusFilter) return false;
      return true;
    });
  }, [payslips, periodFilter, employeeFilter, statusFilter]);

  const summary = useMemo(() => {
    const totalPayslips = filtered.length;
    const totalGross = filtered.reduce((sum, p) => sum + parseFloat(p.gross_pay), 0);
    const totalNet = filtered.reduce((sum, p) => sum + parseFloat(p.net_pay), 0);
    const totalStatutory = filtered.reduce(
      (sum, p) =>
        sum +
        parseFloat(p.nssf_employee) +
        parseFloat(p.shif_contribution) +
        parseFloat(p.housing_levy) +
        parseFloat(p.paye_tax),
      0
    );
    return { totalPayslips, totalGross, totalNet, totalStatutory };
  }, [filtered]);

  const chartData = useMemo(() => {
    const byPeriod: Record<string, number> = {};
    filtered.forEach((p) => {
      byPeriod[p.period_detail] = (byPeriod[p.period_detail] ?? 0) + parseFloat(p.net_pay);
    });
    return Object.entries(byPeriod).sort(([a], [b]) => a.localeCompare(b));
  }, [filtered]);

  const maxNet = Math.max(1, ...chartData.map(([, v]) => v));

  function exportPDF() {
    const doc = new jsPDF({ orientation: 'landscape' });
    doc.setFontSize(16);
    doc.text('Payslip Report', 14, 16);
    doc.setFontSize(10);
    doc.text(`Generated: ${new Date().toLocaleDateString('en-KE')}`, 14, 23);

    autoTable(doc, {
      startY: 30,
      head: [['Employee', 'Period', 'Gross Pay', 'Statutory Deductions', 'Net Pay', 'Status']],
      body: filtered.map((p) => [
        p.employee_name,
        p.period_detail,
        formatKES(parseFloat(p.gross_pay)),
        formatKES(
          parseFloat(p.nssf_employee) +
            parseFloat(p.shif_contribution) +
            parseFloat(p.housing_levy) +
            parseFloat(p.paye_tax)
        ),
        formatKES(parseFloat(p.net_pay)),
        p.status,
      ]),
      styles: { fontSize: 9, cellPadding: 3 },
      headStyles: { fillColor: [27, 42, 110] },
    });

    const pageHeight = doc.internal.pageSize.getHeight();
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text('Generated by Erip Technologies · 0710951879', 14, pageHeight - 10);

    doc.save(`payslip-report-${new Date().toISOString().slice(0, 10)}.pdf`);
  }

  function exportExcel() {
    const worksheet = XLSX.utils.json_to_sheet(
      filtered.map((p) => ({
        Employee: p.employee_name,
        Period: p.period_detail,
        'Gross Pay': parseFloat(p.gross_pay),
        NSSF: parseFloat(p.nssf_employee),
        SHIF: parseFloat(p.shif_contribution),
        'Housing Levy': parseFloat(p.housing_levy),
        PAYE: parseFloat(p.paye_tax),
        'Other Deductions': parseFloat(p.total_other_deductions),
        'Net Pay': parseFloat(p.net_pay),
        Status: p.status,
      }))
    );
    const workbook = XLSX.utils.book_new();
    workbook.Props = { Author: 'Erip Technologies', Company: 'Crimecurb Security Services' };
    XLSX.utils.book_append_sheet(workbook, worksheet, 'Payslips');
    XLSX.writeFile(workbook, `payslip-report-${new Date().toISOString().slice(0, 10)}.xlsx`);
  }

  return (
    <div>
      <Link to="/reports" className="inline-flex items-center gap-1 text-sm text-slate-500 hover:text-slate-700 mb-4 print:hidden">
        <ArrowLeft size={14} /> Back to Reports
      </Link>

      <div className="flex items-start justify-between flex-wrap gap-3 mb-6">
        <div>
          <p className="text-[11px] font-mono font-semibold uppercase tracking-[2px] text-crimecurb-red mb-1">
            Human Resources · Reports
          </p>
          <h1 className="font-display text-2xl font-bold text-slate-800">Payslip Report</h1>
        </div>
        <div className="flex gap-2 print:hidden">
          <button
            onClick={exportPDF}
            className="flex items-center gap-1.5 bg-white border border-slate-200 hover:border-slate-300 text-slate-700 text-sm font-medium px-3 py-2 rounded-lg transition-colors"
          >
            <Download size={14} /> PDF
          </button>
          <button
            onClick={exportExcel}
            className="flex items-center gap-1.5 bg-white border border-slate-200 hover:border-slate-300 text-slate-700 text-sm font-medium px-3 py-2 rounded-lg transition-colors"
          >
            <FileSpreadsheet size={14} /> Excel
          </button>
          <button
            onClick={() => window.print()}
            className="flex items-center gap-1.5 bg-crimecurb-navy hover:opacity-90 text-white text-sm font-medium px-3 py-2 rounded-lg transition-colors"
          >
            <Printer size={14} /> Print
          </button>
        </div>
      </div>

      {/* Filters */}
      <div className="bg-white rounded-xl border border-slate-200 p-4 mb-6 grid grid-cols-1 sm:grid-cols-3 gap-3 print:hidden">
        <div>
          <label className="block text-xs text-slate-500 mb-1">Period</label>
          <select
            value={periodFilter}
            onChange={(e) => setPeriodFilter(e.target.value)}
            className="w-full px-3 py-2 rounded border border-slate-300 text-sm"
          >
            <option value="">All Periods</option>
            {periods.map((p) => (
              <option key={p.id} value={p.id}>{p.period_start} – {p.period_end}</option>
            ))}
          </select>
        </div>
        <div>
          <label className="block text-xs text-slate-500 mb-1">Employee</label>
          <select
            value={employeeFilter}
            onChange={(e) => setEmployeeFilter(e.target.value)}
            className="w-full px-3 py-2 rounded border border-slate-300 text-sm"
          >
            <option value="">All Employees</option>
            {employees.map((e) => (
              <option key={e.id} value={e.user.email}>
                {e.user.first_name} {e.user.last_name}
              </option>
            ))}
          </select>
        </div>
        <div>
          <label className="block text-xs text-slate-500 mb-1">Status</label>
          <select
            value={statusFilter}
            onChange={(e) => setStatusFilter(e.target.value)}
            className="w-full px-3 py-2 rounded border border-slate-300 text-sm"
          >
            <option value="">All Statuses</option>
            {STATUSES.map((s) => (
              <option key={s} value={s}>{s}</option>
            ))}
          </select>
        </div>
      </div>

      {isLoading && <p className="text-slate-500">Loading...</p>}
      {error && <p className="text-red-600">{error}</p>}

      {!isLoading && !error && (
        <>
          {/* Summary cards */}
          <div className="grid grid-cols-2 lg:grid-cols-4 gap-3.5 mb-6">
            <div className="bg-white rounded-xl border border-slate-200 p-4">
              <p className="text-[10.5px] font-semibold uppercase tracking-wide text-slate-500 mb-1">Total Payslips</p>
              <p className="font-mono text-2xl font-bold text-slate-800">{summary.totalPayslips}</p>
            </div>
            <div className="bg-white rounded-xl border border-slate-200 p-4">
              <p className="text-[10.5px] font-semibold uppercase tracking-wide text-slate-500 mb-1">Total Gross Pay</p>
              <p className="font-mono text-2xl font-bold text-slate-800">{formatKES(summary.totalGross)}</p>
            </div>
            <div className="bg-white rounded-xl border border-slate-200 p-4">
              <p className="text-[10.5px] font-semibold uppercase tracking-wide text-slate-500 mb-1">Statutory Deductions</p>
              <p className="font-mono text-2xl font-bold text-slate-800">{formatKES(summary.totalStatutory)}</p>
            </div>
            <div className="bg-white rounded-xl border border-slate-200 p-4">
              <p className="text-[10.5px] font-semibold uppercase tracking-wide text-slate-500 mb-1">Total Net Pay</p>
              <p className="font-mono text-2xl font-bold text-slate-800">{formatKES(summary.totalNet)}</p>
            </div>
          </div>

          {/* Chart */}
          {chartData.length > 0 && (
            <div className="bg-white rounded-xl border border-slate-200 p-4 mb-6">
              <p className="text-xs font-semibold uppercase tracking-wide text-slate-500 mb-4">
                Net Pay by Period
              </p>
              <div className="flex items-end gap-2 h-32">
                {chartData.map(([period, total]) => (
                  <div key={period} className="flex-1 flex flex-col items-center gap-1">
                    <div
                      className="w-full bg-crimecurb-navy rounded-t"
                      style={{ height: `${(total / maxNet) * 100}%`, minHeight: '4px' }}
                      title={`${period}: ${formatKES(total)}`}
                    />
                    <p className="text-[9px] text-slate-400 rotate-45 origin-left whitespace-nowrap mt-1">
                      {period}
                    </p>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Table */}
          <div className="bg-white rounded-xl border border-slate-200 overflow-hidden">
            <table className="w-full text-sm text-left">
              <thead className="bg-slate-50 text-slate-500 uppercase text-xs">
                <tr>
                  <th className="px-4 py-3">Employee</th>
                  <th className="px-4 py-3">Period</th>
                  <th className="px-4 py-3">Gross Pay</th>
                  <th className="px-4 py-3">Statutory Deductions</th>
                  <th className="px-4 py-3">Net Pay</th>
                  <th className="px-4 py-3">Status</th>
                </tr>
              </thead>
              <tbody>
                {filtered.map((p) => (
                  <tr key={p.id} className="border-t border-slate-100">
                    <td className="px-4 py-3 font-medium text-slate-800">{p.employee_name}</td>
                    <td className="px-4 py-3 text-slate-600">{p.period_detail}</td>
                    <td className="px-4 py-3 text-slate-600">{formatKES(parseFloat(p.gross_pay))}</td>
                    <td className="px-4 py-3 text-slate-600">
                      {formatKES(
                        parseFloat(p.nssf_employee) +
                          parseFloat(p.shif_contribution) +
                          parseFloat(p.housing_levy) +
                          parseFloat(p.paye_tax)
                      )}
                    </td>
                    <td className="px-4 py-3 font-medium text-slate-800">{formatKES(parseFloat(p.net_pay))}</td>
                    <td className="px-4 py-3">
                      <span
                        className={`px-2 py-1 rounded text-xs font-medium ${
                          p.status === 'PAID'
                            ? 'bg-emerald-100 text-emerald-700'
                            : p.status === 'APPROVED'
                            ? 'bg-blue-100 text-blue-700'
                            : 'bg-slate-100 text-slate-600'
                        }`}
                      >
                        {p.status}
                      </span>
                    </td>
                  </tr>
                ))}
                {filtered.length === 0 && (
                  <tr>
                    <td colSpan={6} className="px-4 py-6 text-center text-slate-400">
                      No payslips match these filters.
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>

          <div className="text-center text-xs text-slate-400 mt-8 pt-4 border-t border-slate-200">
            <p>
              Generated by Erip <span className="text-crimecurb-red font-semibold">⚡</span> Technologies
            </p>
            <p>0710951879</p>
          </div>
        </>
      )}
    </div>
  );
}