import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, Download, FileSpreadsheet, Printer } from 'lucide-react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';
import { getInvoices } from '../../api/invoicesApi';
import { getClients } from '../../api/sitesApi';
import type { Invoice } from '../../types/invoices';
import type { Client } from '../../types/sites';

function formatKES(value: number): string {
  return new Intl.NumberFormat('en-KE', { style: 'currency', currency: 'KES', maximumFractionDigits: 0 }).format(value);
}

export default function RevenueReportPage() {
  const [invoices, setInvoices] = useState<Invoice[]>([]);
  const [clients, setClients] = useState<Client[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const [startDate, setStartDate] = useState('');
  const [endDate, setEndDate] = useState('');
  const [clientFilter, setClientFilter] = useState('');

  useEffect(() => {
    Promise.all([getInvoices(), getClients()])
      .then(([i, c]) => {
        setInvoices(i);
        setClients(c);
      })
      .catch(() => setError('Failed to load revenue data.'))
      .finally(() => setIsLoading(false));
  }, []);

  const filtered = useMemo(() => {
    return invoices.filter((inv) => {
      if (startDate && inv.issue_date < startDate) return false;
      if (endDate && inv.issue_date > endDate) return false;
      if (clientFilter && inv.client_name !== clientFilter) return false;
      // Revenue report counts billed amounts regardless of paid/unpaid,
      // but excludes cancelled invoices — those were never actually billed out.
      if (inv.status === 'CANCELLED') return false;
      return true;
    });
  }, [invoices, startDate, endDate, clientFilter]);

  const summary = useMemo(() => {
    const totalBilled = filtered.reduce((sum, inv) => sum + Number(inv.subtotal), 0);
    const totalPaid = filtered.filter((inv) => inv.status === 'PAID').reduce((sum, inv) => sum + Number(inv.subtotal), 0);
    const totalOutstanding = totalBilled - totalPaid;
    const invoiceCount = filtered.length;
    return { totalBilled, totalPaid, totalOutstanding, invoiceCount };
  }, [filtered]);

  const chartData = useMemo(() => {
    const byClient: Record<string, number> = {};
    filtered.forEach((inv) => {
      byClient[inv.client_name] = (byClient[inv.client_name] ?? 0) + Number(inv.subtotal);
    });
    return Object.entries(byClient).sort(([, a], [, b]) => b - a).slice(0, 10);
  }, [filtered]);

  const maxAmount = Math.max(1, ...chartData.map(([, a]) => a));

  function exportPDF() {
    const doc = new jsPDF({ orientation: 'landscape' });
    doc.setFontSize(16);
    doc.text('Revenue Report', 14, 16);
    doc.setFontSize(10);
    doc.text(`Generated: ${new Date().toLocaleDateString('en-KE')}`, 14, 23);
    if (startDate || endDate) {
      doc.text(`Period: ${startDate || 'Start'} to ${endDate || 'End'}`, 14, 29);
    }

    autoTable(doc, {
      startY: 35,
      head: [['Invoice #', 'Client', 'Issue Date', 'Due Date', 'Amount', 'Status']],
      body: filtered.map((inv) => [
        inv.invoice_number,
        inv.client_name,
        inv.issue_date,
        inv.due_date,
        formatKES(Number(inv.subtotal)),
        inv.status,
      ]),
      styles: { fontSize: 9, cellPadding: 3 },
      headStyles: { fillColor: [27, 42, 110] },
    });
    const pageHeight = doc.internal.pageSize.getHeight();
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text('Generated by Erip Technologies · 0710951879', 14, pageHeight - 10);

    doc.save(`revenue-report-${new Date().toISOString().slice(0, 10)}.pdf`);
  }

  function exportExcel() {
    const worksheet = XLSX.utils.json_to_sheet(
      filtered.map((inv) => ({
        'Invoice #': inv.invoice_number,
        Client: inv.client_name,
        'Issue Date': inv.issue_date,
        'Due Date': inv.due_date,
        Amount: formatKES(Number(inv.subtotal)),
        Status: inv.status,
      }))
    );
    const workbook = XLSX.utils.book_new();
    workbook.Props = { Author: 'Erip Technologies', Company: 'Crimecurb Security Services' };
    XLSX.utils.book_append_sheet(workbook, worksheet, 'Revenue');
    XLSX.writeFile(workbook, `revenue-report-${new Date().toISOString().slice(0, 10)}.xlsx`);
  }

  return (
    <div>
      <Link to="/reports" className="inline-flex items-center gap-1 text-sm text-slate-500 hover:text-slate-700 mb-4 print:hidden">
        <ArrowLeft size={14} /> Back to Reports
      </Link>

      <div className="flex items-start justify-between flex-wrap gap-3 mb-6">
        <div>
          <p className="text-[11px] font-mono font-semibold uppercase tracking-[2px] text-crimecurb-red mb-1">
            Financial · Reports
          </p>
          <h1 className="font-display text-2xl font-bold text-slate-800">Revenue Report</h1>
        </div>
        <div className="flex gap-2 print:hidden">
          <button onClick={exportPDF} className="flex items-center gap-1.5 bg-white border border-slate-200 hover:border-slate-300 text-slate-700 text-sm font-medium px-3 py-2 rounded-lg transition-colors">
            <Download size={14} /> PDF
          </button>
          <button onClick={exportExcel} className="flex items-center gap-1.5 bg-white border border-slate-200 hover:border-slate-300 text-slate-700 text-sm font-medium px-3 py-2 rounded-lg transition-colors">
            <FileSpreadsheet size={14} /> Excel
          </button>
          <button onClick={() => window.print()} className="flex items-center gap-1.5 bg-crimecurb-navy hover:opacity-90 text-white text-sm font-medium px-3 py-2 rounded-lg transition-colors">
            <Printer size={14} /> Print
          </button>
        </div>
      </div>

      <div className="bg-white rounded-xl border border-slate-200 p-4 mb-6 grid grid-cols-1 sm:grid-cols-3 gap-3 print:hidden">
        <div>
          <label className="block text-xs text-slate-500 mb-1">Start Date</label>
          <input type="date" value={startDate} onChange={(e) => setStartDate(e.target.value)} className="w-full px-3 py-2 rounded border border-slate-300 text-sm" />
        </div>
        <div>
          <label className="block text-xs text-slate-500 mb-1">End Date</label>
          <input type="date" value={endDate} onChange={(e) => setEndDate(e.target.value)} className="w-full px-3 py-2 rounded border border-slate-300 text-sm" />
        </div>
        <div>
          <label className="block text-xs text-slate-500 mb-1">Client</label>
          <select value={clientFilter} onChange={(e) => setClientFilter(e.target.value)} className="w-full px-3 py-2 rounded border border-slate-300 text-sm">
            <option value="">All Clients</option>
            {clients.map((c) => <option key={c.id} value={c.name}>{c.name}</option>)}
          </select>
        </div>
      </div>

      {isLoading && <p className="text-slate-500">Loading...</p>}
      {error && <p className="text-red-600">{error}</p>}

      {!isLoading && !error && (
        <>
          <div className="grid grid-cols-2 lg:grid-cols-4 gap-3.5 mb-6">
            <div className="bg-white rounded-xl border border-slate-200 p-4">
              <p className="text-[10.5px] font-semibold uppercase tracking-wide text-slate-500 mb-1">Total Billed</p>
              <p className="font-mono text-2xl font-bold text-slate-800">{formatKES(summary.totalBilled)}</p>
            </div>
            <div className="bg-white rounded-xl border border-slate-200 p-4">
              <p className="text-[10.5px] font-semibold uppercase tracking-wide text-slate-500 mb-1">Total Paid</p>
              <p className="font-mono text-2xl font-bold text-slate-800">{formatKES(summary.totalPaid)}</p>
            </div>
            <div className="bg-white rounded-xl border border-slate-200 p-4">
              <p className="text-[10.5px] font-semibold uppercase tracking-wide text-slate-500 mb-1">Outstanding</p>
              <p className="font-mono text-2xl font-bold text-slate-800">{formatKES(summary.totalOutstanding)}</p>
            </div>
            <div className="bg-white rounded-xl border border-slate-200 p-4">
              <p className="text-[10.5px] font-semibold uppercase tracking-wide text-slate-500 mb-1">Invoice Count</p>
              <p className="font-mono text-2xl font-bold text-slate-800">{summary.invoiceCount}</p>
            </div>
          </div>

          {chartData.length > 0 && (
            <div className="bg-white rounded-xl border border-slate-200 p-4 mb-6">
              <p className="text-xs font-semibold uppercase tracking-wide text-slate-500 mb-4">Revenue by Client</p>
              <div className="flex items-end gap-3 h-32">
                {chartData.map(([client, amount]) => (
                  <div key={client} className="flex-1 flex flex-col items-center gap-1">
                    <div className="w-full bg-crimecurb-navy rounded-t" style={{ height: `${(amount / maxAmount) * 100}%`, minHeight: '4px' }} title={`${client}: ${formatKES(amount)}`} />
                    <p className="text-[9px] text-slate-400 whitespace-nowrap mt-1 truncate max-w-[60px]">{client}</p>
                  </div>
                ))}
              </div>
            </div>
          )}

          <div className="bg-white rounded-xl border border-slate-200 overflow-x-auto">
            <table className="w-full text-sm text-left whitespace-nowrap">
              <thead className="bg-slate-50 text-slate-500 uppercase text-xs">
                <tr>
                  <th className="px-4 py-3">Invoice #</th>
                  <th className="px-4 py-3">Client</th>
                  <th className="px-4 py-3">Issue Date</th>
                  <th className="px-4 py-3">Due Date</th>
                  <th className="px-4 py-3">Amount</th>
                  <th className="px-4 py-3">Status</th>
                </tr>
              </thead>
              <tbody>
                {filtered.map((inv) => (
                  <tr key={inv.id} className="border-t border-slate-100">
                    <td className="px-4 py-3 font-medium text-slate-800">{inv.invoice_number}</td>
                    <td className="px-4 py-3 text-slate-600">{inv.client_name}</td>
                    <td className="px-4 py-3 text-slate-600">{inv.issue_date}</td>
                    <td className="px-4 py-3 text-slate-600">{inv.due_date}</td>
                    <td className="px-4 py-3 text-slate-600">{formatKES(Number(inv.subtotal))}</td>
                    <td className="px-4 py-3">
                      <span className={`px-2 py-1 rounded text-xs font-medium ${inv.status === 'PAID' ? 'bg-emerald-100 text-emerald-700' : inv.status === 'OVERDUE' ? 'bg-red-100 text-red-700' : 'bg-slate-100 text-slate-600'}`}>
                        {inv.status}
                      </span>
                    </td>
                  </tr>
                ))}
                {filtered.length === 0 && (
                  <tr><td colSpan={6} className="px-4 py-6 text-center text-slate-400">No invoices match these filters.</td></tr>
                )}
              </tbody>
            </table>
          </div>

          <div className="text-center text-xs text-slate-400 mt-8 pt-4 border-t border-slate-200">
            <p>Generated by Erip <span className="text-crimecurb-red font-semibold">⚡</span> Technologies</p>
            <p>0710951879</p>
          </div>
        </>
      )}
    </div>
  );
}