import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, Download, FileSpreadsheet, Printer } from 'lucide-react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';
import { getEmployeeProfiles } from '../../api/staffApi';
import { getSalaryStructures } from '../../api/payrollApi';
import type { EmployeeProfile } from '../../types/staff';
import type { SalaryStructure } from '../../types/payroll';

function formatKES(value: string | number): string {
  const num = typeof value === 'string' ? parseFloat(value) : value;
  return new Intl.NumberFormat('en-KE', { style: 'currency', currency: 'KES', maximumFractionDigits: 0 }).format(num);
}

function getCurrentStructure(structures: SalaryStructure[]): SalaryStructure | null {
  const today = new Date().toISOString().slice(0, 10);
  const active = structures.filter(
    (s) => s.is_active && s.effective_from <= today && (!s.effective_to || s.effective_to >= today)
  );
  if (active.length === 0) return null;
  return active.reduce((latest, s) => (s.effective_from > latest.effective_from ? s : latest));
}

interface Row {
  employee: EmployeeProfile;
  structure: SalaryStructure | null;
}

export default function SalaryStructureReportPage() {
  const [rows, setRows] = useState<Row[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [frequencyFilter, setFrequencyFilter] = useState('');

  useEffect(() => {
    getEmployeeProfiles()
      .then(async (employees) => {
        const results = await Promise.allSettled(
          employees.map((e) => getSalaryStructures(e.id))
        );
        const built: Row[] = employees.map((e, i) => {
          const result = results[i];
          const structures = result.status === 'fulfilled' ? result.value : [];
          return { employee: e, structure: getCurrentStructure(structures) };
        });
        setRows(built);
      })
      .catch(() => setError('Failed to load salary structure data.'))
      .finally(() => setIsLoading(false));
  }, []);

  const filtered = useMemo(() => {
    return rows.filter((r) => {
      if (!r.structure) return false; // report only shows those with an active structure
      if (frequencyFilter && r.structure.payment_frequency !== frequencyFilter) return false;
      return true;
    });
  }, [rows, frequencyFilter]);

  const summary = useMemo(() => {
    const total = filtered.length;
    const totalMonthly = filtered.reduce((sum, r) => sum + (r.structure ? parseFloat(r.structure.basic_salary) : 0), 0);
    const avg = total > 0 ? totalMonthly / total : 0;
    const withoutStructure = rows.filter((r) => !r.structure).length;
    return { total, totalMonthly, avg, withoutStructure };
  }, [filtered, rows]);

  function exportPDF() {
    const doc = new jsPDF({ orientation: 'landscape' });
    doc.setFontSize(16);
    doc.text('Salary Structure Report', 14, 16);
    doc.setFontSize(10);
    doc.text(`Generated: ${new Date().toLocaleDateString('en-KE')}`, 14, 23);

    autoTable(doc, {
      startY: 32,
      head: [['Employee #', 'Name', 'Basic Salary', 'Frequency', 'Effective From', 'Overtime Rate']],
      body: filtered.map((r) => [
        r.employee.employee_number ?? '—',
        `${r.employee.user.first_name} ${r.employee.user.last_name}`,
        formatKES(r.structure!.basic_salary),
        r.structure!.payment_frequency,
        r.structure!.effective_from,
        r.structure!.overtime_rate ? formatKES(r.structure!.overtime_rate) : '—',
      ]),
      styles: { fontSize: 9, cellPadding: 3 },
      headStyles: { fillColor: [27, 42, 110] },
    });
    const pageHeight = doc.internal.pageSize.getHeight();
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text('Generated by Erip Technologies · 0710951879', 14, pageHeight - 10);

    doc.save(`salary-structure-report-${new Date().toISOString().slice(0, 10)}.pdf`);
  }

  function exportExcel() {
    const worksheet = XLSX.utils.json_to_sheet(
      filtered.map((r) => ({
        'Employee #': r.employee.employee_number ?? '—',
        Name: `${r.employee.user.first_name} ${r.employee.user.last_name}`,
        'Basic Salary': formatKES(r.structure!.basic_salary),
        Frequency: r.structure!.payment_frequency,
        'Effective From': r.structure!.effective_from,
        'Overtime Rate': r.structure!.overtime_rate ? formatKES(r.structure!.overtime_rate) : '—',
      }))
    );
    const workbook = XLSX.utils.book_new();
    workbook.Props = { Author: 'Erip Technologies', Company: 'Crimecurb Security Services' };
    XLSX.utils.book_append_sheet(workbook, worksheet, 'Salary Structures');
    XLSX.writeFile(workbook, `salary-structure-report-${new Date().toISOString().slice(0, 10)}.xlsx`);
  }

  return (
    <div>
      <Link to="/reports" className="inline-flex items-center gap-1 text-sm text-slate-500 hover:text-slate-700 mb-4 print:hidden">
        <ArrowLeft size={14} /> Back to Reports
      </Link>

      <div className="flex items-start justify-between flex-wrap gap-3 mb-6">
        <div>
          <p className="text-[11px] font-mono font-semibold uppercase tracking-[2px] text-crimecurb-red mb-1">
            Human Resources · Reports
          </p>
          <h1 className="font-display text-2xl font-bold text-slate-800">Salary Structure Report</h1>
        </div>
        <div className="flex gap-2 print:hidden">
          <button onClick={exportPDF} className="flex items-center gap-1.5 bg-white border border-slate-200 hover:border-slate-300 text-slate-700 text-sm font-medium px-3 py-2 rounded-lg transition-colors">
            <Download size={14} /> PDF
          </button>
          <button onClick={exportExcel} className="flex items-center gap-1.5 bg-white border border-slate-200 hover:border-slate-300 text-slate-700 text-sm font-medium px-3 py-2 rounded-lg transition-colors">
            <FileSpreadsheet size={14} /> Excel
          </button>
          <button onClick={() => window.print()} className="flex items-center gap-1.5 bg-crimecurb-navy hover:opacity-90 text-white text-sm font-medium px-3 py-2 rounded-lg transition-colors">
            <Printer size={14} /> Print
          </button>
        </div>
      </div>

      <div className="bg-white rounded-xl border border-slate-200 p-4 mb-6 grid grid-cols-1 sm:grid-cols-2 gap-3 print:hidden">
        <div>
          <label className="block text-xs text-slate-500 mb-1">Payment Frequency</label>
          <select value={frequencyFilter} onChange={(e) => setFrequencyFilter(e.target.value)} className="w-full px-3 py-2 rounded border border-slate-300 text-sm">
            <option value="">All Frequencies</option>
            <option value="MONTHLY">Monthly</option>
            <option value="WEEKLY">Weekly</option>
            <option value="BI_WEEKLY">Bi-Weekly</option>
          </select>
        </div>
      </div>

      {isLoading && <p className="text-slate-500">Loading...</p>}
      {error && <p className="text-red-600">{error}</p>}

      {!isLoading && !error && (
        <>
          <div className="grid grid-cols-2 lg:grid-cols-4 gap-3.5 mb-6">
            <div className="bg-white rounded-xl border border-slate-200 p-4">
              <p className="text-[10.5px] font-semibold uppercase tracking-wide text-slate-500 mb-1">With Active Structure</p>
              <p className="font-mono text-2xl font-bold text-slate-800">{summary.total}</p>
            </div>
            <div className="bg-white rounded-xl border border-slate-200 p-4">
              <p className="text-[10.5px] font-semibold uppercase tracking-wide text-slate-500 mb-1">Total Basic Salary</p>
              <p className="font-mono text-2xl font-bold text-slate-800">{formatKES(summary.totalMonthly)}</p>
            </div>
            <div className="bg-white rounded-xl border border-slate-200 p-4">
              <p className="text-[10.5px] font-semibold uppercase tracking-wide text-slate-500 mb-1">Average Salary</p>
              <p className="font-mono text-2xl font-bold text-slate-800">{formatKES(summary.avg)}</p>
            </div>
            <div className="bg-white rounded-xl border border-slate-200 p-4">
              <p className="text-[10.5px] font-semibold uppercase tracking-wide text-slate-500 mb-1">Without Structure</p>
              <p className="font-mono text-2xl font-bold text-slate-800">{summary.withoutStructure}</p>
            </div>
          </div>

          <div className="bg-white rounded-xl border border-slate-200 overflow-x-auto">
            <table className="w-full text-sm text-left whitespace-nowrap">
              <thead className="bg-slate-50 text-slate-500 uppercase text-xs">
                <tr>
                  <th className="px-4 py-3">Employee #</th>
                  <th className="px-4 py-3">Name</th>
                  <th className="px-4 py-3">Basic Salary</th>
                  <th className="px-4 py-3">Frequency</th>
                  <th className="px-4 py-3">Effective From</th>
                  <th className="px-4 py-3">Overtime Rate</th>
                </tr>
              </thead>
              <tbody>
                {filtered.map((r) => (
                  <tr key={r.employee.id} className="border-t border-slate-100">
                    <td className="px-4 py-3 font-medium text-slate-800">{r.employee.employee_number ?? '—'}</td>
                    <td className="px-4 py-3 text-slate-600">{r.employee.user.first_name} {r.employee.user.last_name}</td>
                    <td className="px-4 py-3 text-slate-600">{formatKES(r.structure!.basic_salary)}</td>
                    <td className="px-4 py-3 text-slate-600">{r.structure!.payment_frequency}</td>
                    <td className="px-4 py-3 text-slate-600">{r.structure!.effective_from}</td>
                    <td className="px-4 py-3 text-slate-600">{r.structure!.overtime_rate ? formatKES(r.structure!.overtime_rate) : '—'}</td>
                  </tr>
                ))}
                {filtered.length === 0 && (
                  <tr><td colSpan={6} className="px-4 py-6 text-center text-slate-400">No salary structures match these filters.</td></tr>
                )}
              </tbody>
            </table>
          </div>

          <div className="text-center text-xs text-slate-400 mt-8 pt-4 border-t border-slate-200">
            <p>Generated by Erip <span className="text-crimecurb-red font-semibold">⚡</span> Technologies</p>
            <p>0710951879</p>
          </div>
        </>
      )}
    </div>
  );
}