import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, Download, FileSpreadsheet, Printer } from 'lucide-react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';
import { getShifts, getShiftAssignments } from '../../api/shiftsApi';
import { getSites } from '../../api/sitesApi';
import type { Shift, ShiftAssignment } from '../../types/shifts';
import type { Site } from '../../types/sites';

export default function ShiftReportPage() {
  const [shifts, setShifts] = useState<Shift[]>([]);
  const [assignments, setAssignments] = useState<ShiftAssignment[]>([]);
  const [sites, setSites] = useState<Site[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const [startDate, setStartDate] = useState('');
  const [endDate, setEndDate] = useState('');
  const [siteFilter, setSiteFilter] = useState('');

  useEffect(() => {
    Promise.all([getShifts(), getShiftAssignments(), getSites()])
      .then(([sh, a, s]) => {
        setShifts(sh);
        setAssignments(a);
        setSites(s);
      })
      .catch((err) => {
        console.error(err);
        setError('Failed to load shift data.');
      })
      .finally(() => setIsLoading(false));
  }, []);

  const assignmentCountByShift = useMemo(() => {
    const map: Record<string, number> = {};
    assignments.forEach((a) => {
      map[a.shift] = (map[a.shift] ?? 0) + 1;
    });
    return map;
  }, [assignments]);

  const rows = useMemo(() => {
    return shifts
      .filter((sh) => {
        if (startDate && sh.date < startDate) return false;
        if (endDate && sh.date > endDate) return false;
        if (siteFilter && sh.site_name !== siteFilter) return false;
        return true;
      })
      .map((sh) => {
        const assigned = assignmentCountByShift[sh.id] ?? 0;
        return {
          ...sh,
          assigned,
          coverageGap: Math.max(sh.required_guards - assigned, 0),
        };
      })
      .sort((a, b) => a.date.localeCompare(b.date));
  }, [shifts, startDate, endDate, siteFilter, assignmentCountByShift]);

  const summary = useMemo(() => {
    const totalShifts = rows.length;
    const fullyStaffed = rows.filter((r) => r.coverageGap === 0).length;
    const understaffed = totalShifts - fullyStaffed;
    const totalGuardsRequired = rows.reduce((sum, r) => sum + r.required_guards, 0);
    return { totalShifts, fullyStaffed, understaffed, totalGuardsRequired };
  }, [rows]);

  function exportPDF() {
    const doc = new jsPDF({ orientation: 'landscape' });
    doc.setFontSize(16);
    doc.text('Shift Report', 14, 16);
    doc.setFontSize(10);
    doc.text(`Generated: ${new Date().toLocaleDateString('en-KE')}`, 14, 23);

    autoTable(doc, {
      startY: 32,
      head: [['Date', 'Site', 'Type', 'Start', 'End', 'Required', 'Assigned', 'Gap']],
      body: rows.map((r) => [
        r.date, r.site_name, r.shift_type, r.start_time, r.end_time,
        r.required_guards, r.assigned, r.coverageGap,
      ]),
      styles: { fontSize: 9, cellPadding: 3 },
      headStyles: { fillColor: [27, 42, 110] },
    });

    const pageHeight = doc.internal.pageSize.getHeight();
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text('Generated by Erip Technologies · 0710951879', 14, pageHeight - 10);
    doc.save(`shift-report-${new Date().toISOString().slice(0, 10)}.pdf`);
  }

  function exportExcel() {
    const worksheet = XLSX.utils.json_to_sheet(
      rows.map((r) => ({
        Date: r.date, Site: r.site_name, Type: r.shift_type,
        Start: r.start_time, End: r.end_time,
        Required: r.required_guards, Assigned: r.assigned, Gap: r.coverageGap,
      }))
    );
    const workbook = XLSX.utils.book_new();
    workbook.Props = { Author: 'Erip Technologies', Company: 'Crimecurb Security Services' };
    XLSX.utils.book_append_sheet(workbook, worksheet, 'Shifts');
    XLSX.writeFile(workbook, `shift-report-${new Date().toISOString().slice(0, 10)}.xlsx`);
  }

  return (
    <div>
      <Link to="/reports" className="inline-flex items-center gap-1 text-sm text-slate-500 hover:text-slate-700 mb-4 print:hidden">
        <ArrowLeft size={14} /> Back to Reports
      </Link>

      <div className="flex items-start justify-between flex-wrap gap-3 mb-6">
        <div>
          <p className="text-[11px] font-mono font-semibold uppercase tracking-[2px] text-crimecurb-red mb-1">
            Operational · Reports
          </p>
          <h1 className="font-display text-2xl font-bold text-slate-800">Shift Report</h1>
        </div>
        <div className="flex gap-2 print:hidden">
          <button onClick={exportPDF} className="flex items-center gap-1.5 bg-white border border-slate-200 hover:border-slate-300 text-slate-700 text-sm font-medium px-3 py-2 rounded-lg transition-colors">
            <Download size={14} /> PDF
          </button>
          <button onClick={exportExcel} className="flex items-center gap-1.5 bg-white border border-slate-200 hover:border-slate-300 text-slate-700 text-sm font-medium px-3 py-2 rounded-lg transition-colors">
            <FileSpreadsheet size={14} /> Excel
          </button>
          <button onClick={() => window.print()} className="flex items-center gap-1.5 bg-crimecurb-navy hover:opacity-90 text-white text-sm font-medium px-3 py-2 rounded-lg transition-colors">
            <Printer size={14} /> Print
          </button>
        </div>
      </div>

      <div className="bg-white rounded-xl border border-slate-200 p-4 mb-6 grid grid-cols-1 sm:grid-cols-3 gap-3 print:hidden">
        <div>
          <label className="block text-xs text-slate-500 mb-1">Start Date</label>
          <input type="date" value={startDate} onChange={(e) => setStartDate(e.target.value)} className="w-full px-3 py-2 rounded border border-slate-300 text-sm" />
        </div>
        <div>
          <label className="block text-xs text-slate-500 mb-1">End Date</label>
          <input type="date" value={endDate} onChange={(e) => setEndDate(e.target.value)} className="w-full px-3 py-2 rounded border border-slate-300 text-sm" />
        </div>
        <div>
          <label className="block text-xs text-slate-500 mb-1">Site</label>
          <select value={siteFilter} onChange={(e) => setSiteFilter(e.target.value)} className="w-full px-3 py-2 rounded border border-slate-300 text-sm">
            <option value="">All Sites</option>
            {sites.map((s) => <option key={s.id} value={s.name}>{s.name}</option>)}
          </select>
        </div>
      </div>

      {isLoading && <p className="text-slate-500">Loading...</p>}
      {error && <p className="text-red-600">{error}</p>}

      {!isLoading && !error && (
        <>
          <div className="grid grid-cols-2 lg:grid-cols-4 gap-3.5 mb-6">
            <div className="bg-white rounded-xl border border-slate-200 p-4">
              <p className="text-[10.5px] font-semibold uppercase tracking-wide text-slate-500 mb-1">Total Shifts</p>
              <p className="font-mono text-2xl font-bold text-slate-800">{summary.totalShifts}</p>
            </div>
            <div className="bg-white rounded-xl border border-slate-200 p-4">
              <p className="text-[10.5px] font-semibold uppercase tracking-wide text-slate-500 mb-1">Fully Staffed</p>
              <p className="font-mono text-2xl font-bold text-emerald-700">{summary.fullyStaffed}</p>
            </div>
            <div className="bg-white rounded-xl border border-slate-200 p-4">
              <p className="text-[10.5px] font-semibold uppercase tracking-wide text-slate-500 mb-1">Understaffed</p>
              <p className="font-mono text-2xl font-bold text-red-700">{summary.understaffed}</p>
            </div>
            <div className="bg-white rounded-xl border border-slate-200 p-4">
              <p className="text-[10.5px] font-semibold uppercase tracking-wide text-slate-500 mb-1">Guards Required</p>
              <p className="font-mono text-2xl font-bold text-slate-800">{summary.totalGuardsRequired}</p>
            </div>
          </div>

          <div className="bg-white rounded-xl border border-slate-200 overflow-hidden">
            <table className="w-full text-sm text-left">
              <thead className="bg-slate-50 text-slate-500 uppercase text-xs">
                <tr>
                  <th className="px-4 py-3">Date</th>
                  <th className="px-4 py-3">Site</th>
                  <th className="px-4 py-3">Type</th>
                  <th className="px-4 py-3">Start</th>
                  <th className="px-4 py-3">End</th>
                  <th className="px-4 py-3">Required</th>
                  <th className="px-4 py-3">Assigned</th>
                  <th className="px-4 py-3">Coverage</th>
                </tr>
              </thead>
              <tbody>
                {rows.map((r) => (
                  <tr key={r.id} className="border-t border-slate-100">
                    <td className="px-4 py-3 font-medium text-slate-800">{r.date}</td>
                    <td className="px-4 py-3 text-slate-600">{r.site_name}</td>
                    <td className="px-4 py-3 text-slate-600">{r.shift_type}</td>
                    <td className="px-4 py-3 text-slate-600">{r.start_time}</td>
                    <td className="px-4 py-3 text-slate-600">{r.end_time}</td>
                    <td className="px-4 py-3 text-slate-600">{r.required_guards}</td>
                    <td className="px-4 py-3 text-slate-600">{r.assigned}</td>
                    <td className="px-4 py-3">
                      <span className={`px-2 py-1 rounded text-xs font-medium ${r.coverageGap === 0 ? 'bg-emerald-100 text-emerald-700' : 'bg-red-100 text-red-700'}`}>
                        {r.coverageGap === 0 ? 'Full' : `Short ${r.coverageGap}`}
                      </span>
                    </td>
                  </tr>
                ))}
                {rows.length === 0 && (
                  <tr><td colSpan={8} className="px-4 py-6 text-center text-slate-400">No shifts match these filters.</td></tr>
                )}
              </tbody>
            </table>
          </div>

          <div className="text-center text-xs text-slate-400 mt-8 pt-4 border-t border-slate-200">
            <p>Generated by Erip <span className="text-crimecurb-red font-semibold">⚡</span> Technologies</p>
            <p>0710951879</p>
          </div>
        </>
      )}
    </div>
  );
}