import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, Download, FileSpreadsheet, Printer } from 'lucide-react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';
import { getSites } from '../../api/sitesApi';
import { getMyIncidents } from '../../api/incidentsApi';
import { getShifts } from '../../api/shiftsApi';
import { getShiftAssignments } from '../../api/shiftsApi';
import type { Site } from '../../types/sites';
import type { Incident } from '../../types/incidents';
import type { Shift, ShiftAssignment } from '../../types/shifts';

const SEVERITY_WEIGHT: Record<string, number> = { LOW: 1, MEDIUM: 2, HIGH: 3, CRITICAL: 4 };

export default function SitePerformanceReportPage() {
  const [sites, setSites] = useState<Site[]>([]);
  const [incidents, setIncidents] = useState<Incident[]>([]);
  const [shifts, setShifts] = useState<Shift[]>([]);
  const [assignments, setAssignments] = useState<ShiftAssignment[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const [startDate, setStartDate] = useState('');
  const [endDate, setEndDate] = useState('');

  useEffect(() => {
    Promise.all([getSites(), getMyIncidents(), getShifts(), getShiftAssignments()])
      .then(([s, i, sh, a]) => {
        setSites(s);
        setIncidents(i);
        setShifts(sh);
        setAssignments(a);
      })
      .catch((err) => {
        console.error(err);
        setError('Failed to load site performance data.');
      })
      .finally(() => setIsLoading(false));
  }, []);

  const assignmentCountByShift = useMemo(() => {
    const map: Record<string, number> = {};
    assignments.forEach((a) => {
      map[a.shift] = (map[a.shift] ?? 0) + 1;
    });
    return map;
  }, [assignments]);

  const rows = useMemo(() => {
    return sites.map((site) => {
      const siteIncidents = incidents.filter((i) => {
        if (i.site_name !== site.name) return false;
        const occurredDate = i.occurred_at.slice(0, 10);
        if (startDate && occurredDate < startDate) return false;
        if (endDate && occurredDate > endDate) return false;
        return true;
      });

      const siteShifts = shifts.filter((sh) => {
        if (sh.site_name !== site.name) return false;
        if (startDate && sh.date < startDate) return false;
        if (endDate && sh.date > endDate) return false;
        return true;
      });

      const totalRequired = siteShifts.reduce((sum, sh) => sum + sh.required_guards, 0);
      const totalAssigned = siteShifts.reduce((sum, sh) => sum + (assignmentCountByShift[sh.id] ?? 0), 0);
      const coverageRate = totalRequired > 0 ? Math.round((Math.min(totalAssigned, totalRequired) / totalRequired) * 100) : 100;

      const avgSeverity =
        siteIncidents.length > 0
          ? siteIncidents.reduce((sum, i) => sum + (SEVERITY_WEIGHT[i.severity] ?? 1), 0) / siteIncidents.length
          : 0;

      return {
        id: site.id,
        name: site.name,
        clientName: site.client_name,
        incidentCount: siteIncidents.length,
        shiftCount: siteShifts.length,
        coverageRate,
        avgSeverity: avgSeverity.toFixed(1),
        isActive: site.is_active,
      };
    });
  }, [sites, incidents, shifts, assignmentCountByShift, startDate, endDate]);

  const summary = useMemo(() => {
    const totalIncidents = rows.reduce((sum, r) => sum + r.incidentCount, 0);
    const avgCoverage = rows.length > 0 ? Math.round(rows.reduce((sum, r) => sum + r.coverageRate, 0) / rows.length) : 0;
    const worstSite = [...rows].sort((a, b) => b.incidentCount - a.incidentCount)[0];
    return { totalSites: rows.length, totalIncidents, avgCoverage, worstSite };
  }, [rows]);

  function exportPDF() {
    const doc = new jsPDF({ orientation: 'landscape' });
    doc.setFontSize(16);
    doc.text('Site Performance Report', 14, 16);
    doc.setFontSize(10);
    doc.text(`Generated: ${new Date().toLocaleDateString('en-KE')}`, 14, 23);

    autoTable(doc, {
      startY: 32,
      head: [['Site', 'Client', 'Incidents', 'Avg. Severity', 'Shifts', 'Coverage Rate']],
      body: rows.map((r) => [
        r.name, r.clientName, r.incidentCount, r.avgSeverity, r.shiftCount, `${r.coverageRate}%`,
      ]),
      styles: { fontSize: 9, cellPadding: 3 },
      headStyles: { fillColor: [27, 42, 110] },
    });

    const pageHeight = doc.internal.pageSize.getHeight();
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text('Generated by Erip Technologies · 0710951879', 14, pageHeight - 10);
    doc.save(`site-performance-report-${new Date().toISOString().slice(0, 10)}.pdf`);
  }

  function exportExcel() {
    const worksheet = XLSX.utils.json_to_sheet(
      rows.map((r) => ({
        Site: r.name, Client: r.clientName, Incidents: r.incidentCount,
        'Avg. Severity': r.avgSeverity, Shifts: r.shiftCount, 'Coverage Rate': `${r.coverageRate}%`,
      }))
    );
    const workbook = XLSX.utils.book_new();
    workbook.Props = { Author: 'Erip Technologies', Company: 'Crimecurb Security Services' };
    XLSX.utils.book_append_sheet(workbook, worksheet, 'Site Performance');
    XLSX.writeFile(workbook, `site-performance-report-${new Date().toISOString().slice(0, 10)}.xlsx`);
  }

  return (
    <div>
      <Link to="/reports" className="inline-flex items-center gap-1 text-sm text-slate-500 hover:text-slate-700 mb-4 print:hidden">
        <ArrowLeft size={14} /> Back to Reports
      </Link>

      <div className="flex items-start justify-between flex-wrap gap-3 mb-6">
        <div>
          <p className="text-[11px] font-mono font-semibold uppercase tracking-[2px] text-crimecurb-red mb-1">
            Operational · Reports
          </p>
          <h1 className="font-display text-2xl font-bold text-slate-800">Site Performance Report</h1>
        </div>
        <div className="flex gap-2 print:hidden">
          <button onClick={exportPDF} className="flex items-center gap-1.5 bg-white border border-slate-200 hover:border-slate-300 text-slate-700 text-sm font-medium px-3 py-2 rounded-lg transition-colors">
            <Download size={14} /> PDF
          </button>
          <button onClick={exportExcel} className="flex items-center gap-1.5 bg-white border border-slate-200 hover:border-slate-300 text-slate-700 text-sm font-medium px-3 py-2 rounded-lg transition-colors">
            <FileSpreadsheet size={14} /> Excel
          </button>
          <button onClick={() => window.print()} className="flex items-center gap-1.5 bg-crimecurb-navy hover:opacity-90 text-white text-sm font-medium px-3 py-2 rounded-lg transition-colors">
            <Printer size={14} /> Print
          </button>
        </div>
      </div>

      <div className="bg-white rounded-xl border border-slate-200 p-4 mb-6 grid grid-cols-1 sm:grid-cols-2 gap-3 print:hidden">
        <div>
          <label className="block text-xs text-slate-500 mb-1">Start Date</label>
          <input type="date" value={startDate} onChange={(e) => setStartDate(e.target.value)} className="w-full px-3 py-2 rounded border border-slate-300 text-sm" />
        </div>
        <div>
          <label className="block text-xs text-slate-500 mb-1">End Date</label>
          <input type="date" value={endDate} onChange={(e) => setEndDate(e.target.value)} className="w-full px-3 py-2 rounded border border-slate-300 text-sm" />
        </div>
      </div>

      {isLoading && <p className="text-slate-500">Loading...</p>}
      {error && <p className="text-red-600">{error}</p>}

      {!isLoading && !error && (
        <>
          <div className="grid grid-cols-2 lg:grid-cols-4 gap-3.5 mb-6">
            <div className="bg-white rounded-xl border border-slate-200 p-4">
              <p className="text-[10.5px] font-semibold uppercase tracking-wide text-slate-500 mb-1">Total Sites</p>
              <p className="font-mono text-2xl font-bold text-slate-800">{summary.totalSites}</p>
            </div>
            <div className="bg-white rounded-xl border border-slate-200 p-4">
              <p className="text-[10.5px] font-semibold uppercase tracking-wide text-slate-500 mb-1">Total Incidents</p>
              <p className="font-mono text-2xl font-bold text-slate-800">{summary.totalIncidents}</p>
            </div>
            <div className="bg-white rounded-xl border border-slate-200 p-4">
              <p className="text-[10.5px] font-semibold uppercase tracking-wide text-slate-500 mb-1">Avg. Coverage</p>
              <p className="font-mono text-2xl font-bold text-slate-800">{summary.avgCoverage}%</p>
            </div>
            <div className="bg-white rounded-xl border border-slate-200 p-4">
              <p className="text-[10.5px] font-semibold uppercase tracking-wide text-slate-500 mb-1">Most Incidents</p>
              <p className="font-mono text-lg font-bold text-red-700 truncate">{summary.worstSite?.name ?? '—'}</p>
            </div>
          </div>

          <div className="bg-white rounded-xl border border-slate-200 overflow-hidden">
            <table className="w-full text-sm text-left">
              <thead className="bg-slate-50 text-slate-500 uppercase text-xs">
                <tr>
                  <th className="px-4 py-3">Site</th>
                  <th className="px-4 py-3">Client</th>
                  <th className="px-4 py-3">Incidents</th>
                  <th className="px-4 py-3">Avg. Severity</th>
                  <th className="px-4 py-3">Shifts</th>
                  <th className="px-4 py-3">Coverage Rate</th>
                </tr>
              </thead>
              <tbody>
                {rows.map((r) => (
                  <tr key={r.id} className="border-t border-slate-100">
                    <td className="px-4 py-3 font-medium text-slate-800">{r.name}</td>
                    <td className="px-4 py-3 text-slate-600">{r.clientName}</td>
                    <td className="px-4 py-3 text-slate-600">{r.incidentCount}</td>
                    <td className="px-4 py-3 text-slate-600">{r.avgSeverity}</td>
                    <td className="px-4 py-3 text-slate-600">{r.shiftCount}</td>
                    <td className="px-4 py-3">
                      <span className={`px-2 py-1 rounded text-xs font-medium ${r.coverageRate >= 90 ? 'bg-emerald-100 text-emerald-700' : r.coverageRate >= 70 ? 'bg-amber-100 text-amber-700' : 'bg-red-100 text-red-700'}`}>
                        {r.coverageRate}%
                      </span>
                    </td>
                  </tr>
                ))}
                {rows.length === 0 && (
                  <tr><td colSpan={6} className="px-4 py-6 text-center text-slate-400">No sites found.</td></tr>
                )}
              </tbody>
            </table>
          </div>

          <div className="text-center text-xs text-slate-400 mt-8 pt-4 border-t border-slate-200">
            <p>Generated by Erip <span className="text-crimecurb-red font-semibold">⚡</span> Technologies</p>
            <p>0710951879</p>
          </div>
        </>
      )}
    </div>
  );
}