import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, Download, FileSpreadsheet, Printer } from 'lucide-react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';
import { getSiteAssignments, getSites } from '../../api/sitesApi';
import { getEmployeeProfiles } from '../../api/staffApi';
import type { SiteAssignment } from '../../types/sites';
import type { Site } from '../../types/sites';
import type { EmployeeProfile } from '../../types/staff';

export default function StaffDeploymentReportPage() {
  const [assignments, setAssignments] = useState<SiteAssignment[]>([]);
  const [sites, setSites] = useState<Site[]>([]);
  const [employees, setEmployees] = useState<EmployeeProfile[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const [siteFilter, setSiteFilter] = useState('');
  const [statusFilter, setStatusFilter] = useState<'' | 'current' | 'ended'>('');

  useEffect(() => {
    Promise.all([getSiteAssignments(), getSites(), getEmployeeProfiles()])
      .then(([a, s, e]) => {
        setAssignments(a);
        setSites(s);
        setEmployees(e);
      })
      .catch(() => setError('Failed to load deployment data.'))
      .finally(() => setIsLoading(false));
  }, []);

  const employeeById = useMemo(() => {
    const map: Record<string, EmployeeProfile> = {};
    employees.forEach((e) => { map[e.id] = e; });
    return map;
  }, [employees]);

  const rows = useMemo(() => {
    return assignments
      .map((a) => {
        const emp = employeeById[a.employee];
        return {
          ...a,
          employeeName: emp ? `${emp.user.first_name} ${emp.user.last_name}` : 'Unknown',
          employeeNumber: emp?.employee_number ?? '—',
          employeeRole: emp?.user.role ?? '—',
          isCurrent: !a.end_date,
        };
      })
      .filter((r) => {
        if (siteFilter && r.site_name !== siteFilter) return false;
        if (statusFilter === 'current' && !r.isCurrent) return false;
        if (statusFilter === 'ended' && r.isCurrent) return false;
        return true;
      });
  }, [assignments, employeeById, siteFilter, statusFilter]);

  const summary = useMemo(() => {
    const total = rows.length;
    const current = rows.filter((r) => r.isCurrent).length;
    const sitesCovered = new Set(rows.map((r) => r.site_name)).size;
    const guardsDeployed = new Set(rows.filter((r) => r.isCurrent && r.employeeRole === 'GUARD').map((r) => r.employee)).size;
    return { total, current, sitesCovered, guardsDeployed };
  }, [rows]);

  const chartData = useMemo(() => {
    const bySite: Record<string, number> = {};
    rows.filter((r) => r.isCurrent).forEach((r) => {
      bySite[r.site_name] = (bySite[r.site_name] ?? 0) + 1;
    });
    return Object.entries(bySite).sort(([, a], [, b]) => b - a).slice(0, 10);
  }, [rows]);

  const maxCount = Math.max(1, ...chartData.map(([, c]) => c));

  function exportPDF() {
    const doc = new jsPDF({ orientation: 'landscape' });
    doc.setFontSize(16);
    doc.text('Staff Deployment Report', 14, 16);
    doc.setFontSize(10);
    doc.text(`Generated: ${new Date().toLocaleDateString('en-KE')}`, 14, 23);

    autoTable(doc, {
      startY: 32,
      head: [['Employee #', 'Name', 'Role', 'Site', 'Start Date', 'End Date', 'Status']],
      body: rows.map((r) => [
        r.employeeNumber,
        r.employeeName,
        r.employeeRole,
        r.site_name,
        r.start_date,
        r.end_date ?? '—',
        r.isCurrent ? 'Current' : 'Ended',
      ]),
      styles: { fontSize: 9, cellPadding: 3 },
      headStyles: { fillColor: [27, 42, 110] },
    });
    const pageHeight = doc.internal.pageSize.getHeight();
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text('Generated by Erip Technologies · 0710951879', 14, pageHeight - 10);

    doc.save(`staff-deployment-report-${new Date().toISOString().slice(0, 10)}.pdf`);
  }

  function exportExcel() {
    const worksheet = XLSX.utils.json_to_sheet(
      rows.map((r) => ({
        'Employee #': r.employeeNumber,
        Name: r.employeeName,
        Role: r.employeeRole,
        Site: r.site_name,
        'Start Date': r.start_date,
        'End Date': r.end_date ?? '—',
        Status: r.isCurrent ? 'Current' : 'Ended',
      }))
    );
    const workbook = XLSX.utils.book_new();
    workbook.Props = { Author: 'Erip Technologies', Company: 'Crimecurb Security Services' };
    XLSX.utils.book_append_sheet(workbook, worksheet, 'Deployment');
    XLSX.writeFile(workbook, `staff-deployment-report-${new Date().toISOString().slice(0, 10)}.xlsx`);
  }

  return (
    <div>
      <Link to="/reports" className="inline-flex items-center gap-1 text-sm text-slate-500 hover:text-slate-700 mb-4 print:hidden">
        <ArrowLeft size={14} /> Back to Reports
      </Link>

      <div className="flex items-start justify-between flex-wrap gap-3 mb-6">
        <div>
          <p className="text-[11px] font-mono font-semibold uppercase tracking-[2px] text-crimecurb-red mb-1">
            Human Resources · Reports
          </p>
          <h1 className="font-display text-2xl font-bold text-slate-800">Staff Deployment Report</h1>
        </div>
        <div className="flex gap-2 print:hidden">
          <button onClick={exportPDF} className="flex items-center gap-1.5 bg-white border border-slate-200 hover:border-slate-300 text-slate-700 text-sm font-medium px-3 py-2 rounded-lg transition-colors">
            <Download size={14} /> PDF
          </button>
          <button onClick={exportExcel} className="flex items-center gap-1.5 bg-white border border-slate-200 hover:border-slate-300 text-slate-700 text-sm font-medium px-3 py-2 rounded-lg transition-colors">
            <FileSpreadsheet size={14} /> Excel
          </button>
          <button onClick={() => window.print()} className="flex items-center gap-1.5 bg-crimecurb-navy hover:opacity-90 text-white text-sm font-medium px-3 py-2 rounded-lg transition-colors">
            <Printer size={14} /> Print
          </button>
        </div>
      </div>

      <div className="bg-white rounded-xl border border-slate-200 p-4 mb-6 grid grid-cols-1 sm:grid-cols-2 gap-3 print:hidden">
        <div>
          <label className="block text-xs text-slate-500 mb-1">Site</label>
          <select value={siteFilter} onChange={(e) => setSiteFilter(e.target.value)} className="w-full px-3 py-2 rounded border border-slate-300 text-sm">
            <option value="">All Sites</option>
            {sites.map((s) => <option key={s.id} value={s.name}>{s.name}</option>)}
          </select>
        </div>
        <div>
          <label className="block text-xs text-slate-500 mb-1">Status</label>
          <select value={statusFilter} onChange={(e) => setStatusFilter(e.target.value as '' | 'current' | 'ended')} className="w-full px-3 py-2 rounded border border-slate-300 text-sm">
            <option value="">All</option>
            <option value="current">Current</option>
            <option value="ended">Ended</option>
          </select>
        </div>
      </div>

      {isLoading && <p className="text-slate-500">Loading...</p>}
      {error && <p className="text-red-600">{error}</p>}

      {!isLoading && !error && (
        <>
          <div className="grid grid-cols-2 lg:grid-cols-4 gap-3.5 mb-6">
            <div className="bg-white rounded-xl border border-slate-200 p-4">
              <p className="text-[10.5px] font-semibold uppercase tracking-wide text-slate-500 mb-1">Total Postings</p>
              <p className="font-mono text-2xl font-bold text-slate-800">{summary.total}</p>
            </div>
            <div className="bg-white rounded-xl border border-slate-200 p-4">
              <p className="text-[10.5px] font-semibold uppercase tracking-wide text-slate-500 mb-1">Current Postings</p>
              <p className="font-mono text-2xl font-bold text-slate-800">{summary.current}</p>
            </div>
            <div className="bg-white rounded-xl border border-slate-200 p-4">
              <p className="text-[10.5px] font-semibold uppercase tracking-wide text-slate-500 mb-1">Sites Covered</p>
              <p className="font-mono text-2xl font-bold text-slate-800">{summary.sitesCovered}</p>
            </div>
            <div className="bg-white rounded-xl border border-slate-200 p-4">
              <p className="text-[10.5px] font-semibold uppercase tracking-wide text-slate-500 mb-1">Guards Deployed</p>
              <p className="font-mono text-2xl font-bold text-slate-800">{summary.guardsDeployed}</p>
            </div>
          </div>

          {chartData.length > 0 && (
            <div className="bg-white rounded-xl border border-slate-200 p-4 mb-6">
              <p className="text-xs font-semibold uppercase tracking-wide text-slate-500 mb-4">Current Postings by Site</p>
              <div className="flex items-end gap-3 h-32">
                {chartData.map(([site, count]) => (
                  <div key={site} className="flex-1 flex flex-col items-center gap-1">
                    <div className="w-full bg-crimecurb-navy rounded-t" style={{ height: `${(count / maxCount) * 100}%`, minHeight: '4px' }} title={`${site}: ${count}`} />
                    <p className="text-[9px] text-slate-400 whitespace-nowrap mt-1 truncate max-w-[60px]">{site}</p>
                  </div>
                ))}
              </div>
            </div>
          )}

          <div className="bg-white rounded-xl border border-slate-200 overflow-x-auto">
            <table className="w-full text-sm text-left whitespace-nowrap">
              <thead className="bg-slate-50 text-slate-500 uppercase text-xs">
                <tr>
                  <th className="px-4 py-3">Employee #</th>
                  <th className="px-4 py-3">Name</th>
                  <th className="px-4 py-3">Role</th>
                  <th className="px-4 py-3">Site</th>
                  <th className="px-4 py-3">Start Date</th>
                  <th className="px-4 py-3">End Date</th>
                  <th className="px-4 py-3">Status</th>
                </tr>
              </thead>
              <tbody>
                {rows.map((r) => (
                  <tr key={r.id} className="border-t border-slate-100">
                    <td className="px-4 py-3 font-medium text-slate-800">{r.employeeNumber}</td>
                    <td className="px-4 py-3 text-slate-600">{r.employeeName}</td>
                    <td className="px-4 py-3 text-slate-600">{r.employeeRole}</td>
                    <td className="px-4 py-3 text-slate-600">{r.site_name}</td>
                    <td className="px-4 py-3 text-slate-600">{r.start_date}</td>
                    <td className="px-4 py-3 text-slate-600">{r.end_date ?? '—'}</td>
                    <td className="px-4 py-3">
                      <span className={`px-2 py-1 rounded text-xs font-medium ${r.isCurrent ? 'bg-emerald-100 text-emerald-700' : 'bg-slate-100 text-slate-600'}`}>
                        {r.isCurrent ? 'Current' : 'Ended'}
                      </span>
                    </td>
                  </tr>
                ))}
                {rows.length === 0 && (
                  <tr><td colSpan={7} className="px-4 py-6 text-center text-slate-400">No deployment records match these filters.</td></tr>
                )}
              </tbody>
            </table>
          </div>

          <div className="text-center text-xs text-slate-400 mt-8 pt-4 border-t border-slate-200">
            <p>Generated by Erip <span className="text-crimecurb-red font-semibold">⚡</span> Technologies</p>
            <p>0710951879</p>
          </div>
        </>
      )}
    </div>
  );
}